### ISSUE TITLE
Search - Undefined index

### ISSUE THREAD

**Issue by G3ph4z** [sipcapture/homer-ui#103]
Hello!

We installed with "Homer Kamailio Installer", and it working for 2-3 minutes, but after that we get many php error, and can't use "SIP Search" panel.

Log:
http://paste.denes.cloud/view/0c9c6618

It cant load more then 100 items. But if we are change the time to two interval (for ex: 12:40 and 12:55) instead of "today".

TL;DR: The search with "Time Range" working fine, but everything else does not work.

(English is not my mother tongue; please excuse any errors on my part.)

**Comment by lmangani** [comment]
Hi @G3ph4z could you provide the installation log from our script?
Also try execute the rotation scripts manually and check if they are in `CRON` for execution first.

**Comment by G3ph4z** [comment]
Hi @lmangani !

Yes, ofc. But can you tell me where can I find the installation log after installation?
The `CRON` and everything else is working fine, except the searching.

**Comment by lmangani** [comment]
The location is outlined in the final output of the installer itself.
Should be in /tmp unless you restarted the server.

I think i maybe misunderstood your question - you do have results with Time Range? In this case, what is the exact problem? please provide a step-by-step procedure to replicate the scenario.

Thanks!

**Comment by G3ph4z** [comment]
I have no error in installer's log.

So, our problem is filtering. When we use the "time range" function its working fine, but if we select "today" or "yesterday" (or any else option) does not show any results, but we have many data at yesterday.

**Comment by lmangani** [comment]
Sounds like a potential timezone setting issue or mixmatch between front-backend and database.
You can inspect the queries HOMER is sending to DB and post them here for discussion by either changing the settings or sniffing the mysql port.

**Comment by G3ph4z** [comment]
Sorry for late reply. both of timezones are correct.

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/releases/tag/1.1.8
