### ISSUE TITLE
clock.js widget DST function is broken

### ISSUE THREAD

**Issue by shaunbro** [sipcapture/homer-ui#104]
Pretty sure the clock DST handling logic is broken. As I understand it (which may be wrong) the code checks to see if the browser time is in DST and then adds +1 to the offset calc for each clock. 

_var d = new Date();
var offset = ltz.offset;
var utc = d.getTime() + (d.getTimezoneOffset() * 60000);
if(d.dst()) offset+=1; 
var date = new Date(utc + (3600000*offset));_

The result is that if DST check happens to be 'True' all clocks are offset regardless of the actual state of DST in the timezone the clock is displaying including UTC (ie everything wrong by 1hr)

looks like all the cool kids are using moment to handle this stuff more easily now.

**Comment by lmangani** [comment]
Most likely true - Next version gets rid of this entirely and uses lbs to figure out time/timezones. If you'd like to file a PR for the 5.x version we'll happily accept it but we're focused on the upcoming seven design which already cured this at the root.

**Comment by shaunbro** [comment]
Thanks, and agree not much point spending time on this given you have replaced it already. The only reason it showed up was because of another issue I had with mismatched server localtimes and this being a default widget caused some confusion.

**Comment by adubovikov** [comment]
sorry, but can you check it with new UI ?
https://github.com/sipcapture/homer-app/releases/tag/1.1.8
