### ISSUE TITLE
Homer logs POST error

### ISSUE THREAD

**Issue by pramsky** [sipcapture/homer-ui#105]
When opening up a the details on a call, I see an error 500 returned after a POST to /api/v1/report/log

When looking at the mysql general log I see:

```sql
SELECT *,'single' as dbnode FROM logs_capture  WHERE (date BETWEEN FROM_UNIXTIME(1538599382) AND FROM_UNIXTIME(1538600100)) AND ( ( correlation_id = '9553135625fb0672b7660db178dbf379' OR correlation_id = '9553135625fb0672b7660db178dbf379_b2b-1' OR correlation_id = '9553135625fb0672b7660db178dbf379_b2b-' OR correlation_id = '9553135625fb0672b7660db178dbf37' )) LIMIT 100
```

When doing a select * from logs_capture, there are 0 entries. I do not see any associated INSERTs into logs_capture or any table with the word logs.

Any thoughts/ideas ? 

Thanks in advance!

**Comment by pramsky** [comment]
Hey @lmangani 

I was trying to get MOS stats to show up ( I get MOS graphs ) and to correlate the carrier leg, looking at the dev tools said there was an error 500 from the POST to /api/v1/report/log. 

I have captagent running sending packets to homer. When opening up a call id, devtools reports the error. 

Looking into kamailio.cfg I see one instance of logging to logs_capture which is under

```
else if($hep(0x00b) == 100){
... stuff ..
$var(table) = "logs_capture";
... stuff ...
sql_query("wc", "INSERT INTO $var(table) (date, micro_ts, correlation_id, source_ip, source_port, destination_ip, destination_port, proto, family, type, node, msg) VALUES($var(t_date), $var(millisec), '$var(correlation_id)','$var(srcip)',$var(srcport),'$var(dstip)',$var(dstport),$var(proto),$var(family),$var(type),'$var(node)','$(var(json){s.escape.common})')");
... stuff ..
}
```

I was not sure if this was causing the MOS stats to not show up. (I get the MOS graph though)

![screen shot 2018-10-03 at 3 36 09 pm](https://user-images.githubusercontent.com/1157297/46443375-20542100-c722-11e8-9303-06e01cbc517b.png)
![screen shot 2018-10-03 at 3 32 38 pm](https://user-images.githubusercontent.com/1157297/46443379-234f1180-c722-11e8-9702-833c7f6ee295.png)

Thanks in advance!

**Comment by pramsky** [comment]
Do you recommend any specific 7x install ? I see 3 docker options. Is there a specific one which is recommended ?

**Comment by lmangani** [comment]
@pramsky you need to check what happens on the server when the 500 error is returned and post here any logs you can retrieve from the webapp. The choice for 7.x depends on your backend preferences mostly, the InfluxDB integration is the one currently able to power internal charts.

**Comment by pramsky** [comment]
The httpd error logs have these php errors.

```
[Wed Oct 03 22:32:55.562445 2018] [:error] [pid 23649] [client 50.125.167.106:49806] PHP Notice:  Undefined index: node in /var/www/html/homer/api/RestApi/Report.php on line 1275
[Wed Oct 03 22:32:55.563441 2018] [:error] [pid 23649] [client 50.125.167.106:49806] PHP Fatal error:  Call to undefined function RestApi\\array_column() in /var/www/html/homer/api/RestApi/Report.php on line 1354
[Wed Oct 03 22:33:07.636564 2018] [:error] [pid 23650] [client 50.125.167.106:49859] PHP Notice:  Undefined index: node in /var/www/html/homer/api/RestApi/Report.php on line 1275
[Wed Oct 03 22:33:07.637566 2018] [:error] [pid 23650] [client 50.125.167.106:49859] PHP Fatal error:  Call to undefined function RestApi\\array_column() in /var/www/html/homer/api/RestApi/Report.php on line 1354
```

**Comment by pramsky** [comment]
@lmangani 

I haven't figured out what the PHP errors are yet, but I was able to get RTCP and RTCP XR stats working. 

I'll dig into the PHP errors and post back what I find 

Thanks for all your help @lmangani
