### ISSUE TITLE
Changing username and password for homer UI from database

### ISSUE THREAD

**Issue by daniruddha29** [sipcapture/homer-ui#107]
Hi All,

I have setup homer 5 with percona and things was working good. We was able to login and do the stuff but somehow someone from the team has changed the password for homer admin account and we lost login to the homer. 
I am the admin and has admin/root access to database and homer system. Can i change the password from database end directly?

Regards,
Aniruddha

**Comment by adubovikov** [comment]
yes, just login to mysql and change the password in the user table. We use the internal PASSWORD function of mysql 

https://github.com/sipcapture/homer-api/blob/master/sql/mysql/schema_configuration.sql#L159-L161
