### ISSUE TITLE
Settings / Mapping : Fields Mapping

### ISSUE THREAD

**Issue by RFbkak37y3kIY** [sipcapture/homer-ui#111]
More comfortable field setup

![image](https://user-images.githubusercontent.com/10195789/72551442-8922c680-389d-11ea-8c27-7a4fefe6134d.png)
![image](https://user-images.githubusercontent.com/10195789/72551461-8f18a780-389d-11ea-9023-4242a087e54c.png)
![image](https://user-images.githubusercontent.com/10195789/72551473-9344c500-389d-11ea-9302-7448ad9fe735.png)
![image](https://user-images.githubusercontent.com/10195789/72551482-98097900-389d-11ea-8cc7-a00f3da98923.png)

**Comment by lmangani** [comment]
Node selection should originate from the underlying homer-app configuration if possible

**Comment by adubovikov** [comment]
There are two ways: static and dynamic over api (form_api). If the field
for_default defined and isn't null we use it, otherwise - the api call
