### ISSUE TITLE
Modal Styling and Index Stacking

### ISSUE THREAD

**Issue by lmangani** [sipcapture/homer-ui#123]
The modals have a couple of shortcomings:

* shadow should be always on to improve visibility  - currently its only on `drag` of modals
* we might need `z-index` classes for the different modal layers to allow proper stacking. Example:
  * `session` modals should be in range `1000-1999` 
  * `message` modals should be in range `2000-2999`

Test: open a session modal in H7.7 and click multiple messages - message details should remain in front of session dialog layers at all times.

**Comment by RFbkak37y3kIY** [comment]
fixed in devel, waiting merge to master branch
