### ISSUE TITLE
Multi Value fields w/ wildcard

### ISSUE THREAD

**Issue by lmangani** [sipcapture/homer-ui#126]
Multi value fields are not correctly detercted when using wildcards. Example

* SIP METHOD: `INVITE;100` - works
* SIP METHOD:  `INV%` - works
* SIP METHOD: `INV%;10%` - fails

**Comment by negbie** [comment]
I think this is more related to homer-app

**Comment by lmangani** [comment]
The actual query works, so it seems related to how its parsed on the field in fragments. Let's see.

**Comment by negbie** [comment]
Fxed in homer-app.
