### ISSUE TITLE
Blurry font under logs tab

### ISSUE THREAD

**Issue by negbie** [sipcapture/homer-ui#163]
![blur](https://user-images.githubusercontent.com/20154956/74608243-cf0ebc80-50df-11ea-9345-9aa12566d5ae.jpeg)

**Comment by negbie** [comment]
Chrome Version 79.0.3945.88 (64-Bit)

**Comment by lmangani** [comment]
@negbie are you using a zoom other than 100% by any chance?

**Comment by negbie** [comment]
@lmangani nope. 100%. I made the screenshot in a way that you can see the other input fields with 111111 aswell. There you can see the font is sharp. You don't have this?

**Comment by lmangani** [comment]
@negbie not really, at least on my system, but i can sort of see it when i scale it down to 80% 
Perhaps other users can check this and help us confirm? Thanks!

**Comment by negbie** [comment]
Or maybe I'm just getting old and see more and more blurry :D Ok lets that this with help wanted.

**Comment by negbie** [comment]
Tested with newest ui and did not have this anymore. So let's close it :)
