### ISSUE TITLE
Possibility to hide HEP types from flow

### ISSUE THREAD

**Issue by negbie** [sipcapture/homer-ui#170]
Is there an advanced setting to hide some HEP Types (for example RTCP) from flow but keep in QOS tab? Changing mapping will remove them completely.

**Comment by adubovikov** [comment]
same idea just came to me. A lot of RTCP packets make the flow unreadable.

**Comment by adubovikov** [comment]
@RFbkak37y3kIY it will be nice to have a slider on right/left that hide/enable existing EVENTs in the Messages and in Flow view.

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/releases/tag/1.1.32
also the packages are in the repository. Please update
