### ISSUE TITLE
time deltas are wrong in flow

### ISSUE THREAD

**Issue by kpribic** [sipcapture/homer-ui#171]
Shown time deltas are completely wrong, messages are roughly a second apart as you can see based on timestamps

![image](https://user-images.githubusercontent.com/50572561/74823418-f4314400-5306-11ea-8494-a215571700a6.png)

This example is for Options but they are wrong for calls as well.

Tested on HOMER 7.7.028(prod)

**Comment by adubovikov** [comment]
as I see it should be 1 sec and 101 ms. or 1.101 sec

**Comment by adubovikov** [comment]
![Screenshot from 2020-02-19 14-40-55](https://user-images.githubusercontent.com/4513061/74839983-7bda7b00-5326-11ea-93f3-0c43335dc743.png)
https://github.com/sipcapture/homer-ui/commit/bf6bc8a15951a834415b82f125428def225a039f

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/releases/tag/1.1.32
also the packages are in the repository
