### ISSUE TITLE
Better tab Opt-in/out defaults

### ISSUE THREAD

**Issue by negbie** [sipcapture/homer-ui#177]
In flow tab I think RTCP should be opt-in for the new proto hider (or if you want to add more logic depending on if proto is 1)

In QOS tab  lost packets, pseudo mos and ia_jitter should be opt-out the rest opt-in. I would even remove lsr and octets.

**Comment by lmangani** [comment]
I think the "opt-in" (or default on) elements should be configurable - different scenarios require different results.

**Comment by negbie** [comment]
Yip that would be even better. Mby via adv. settings?

**Comment by lmangani** [comment]
Yes, We already have advanced settings to select stuff like default tab, etc. We should add options there to define the (optional) defaults for those elements next.
