### ISSUE TITLE
RTCP in DB, but nothing in homer UI

### ISSUE THREAD

**Issue by Sp0rN** [sipcapture/homer-ui#182]
Hi Guys,

Im having issues seeing RTCP in the packets captured by homer.

Essentially every captured call, the SIP info is perfect, and there are QoS stats for it, but in the actual PCAP & Call Flow, there's no RTCP:

Below is the heplify parameters im using:
heplify -i bond0 -pr 5050-5090 -hs my.hep.server:9060 -hn SIPNT3 -d rtcp,rtp,sdp

Below is a screenie of call flow & Messages:
![image](https://user-images.githubusercontent.com/31306657/75780715-92d88e80-5d64-11ea-86c4-740cfbe59613.png)
![image](https://user-images.githubusercontent.com/31306657/75780733-9835d900-5d64-11ea-84b2-fdd03e373b0d.png)

Im currently using Homer7 Docker (hom7-promall), with heplify v1.56 on my freeswitch boxes.

This issue was raised under heplify repo:

I confirmed with @negbie that there is legitimate RTCP info within the homer_data db for calls, thus ruling out a heplify-server issue, right?

https://github.com/sipcapture/heplify/issues/159

But in Summary I have tried the below:
1. Confirmed heplify parameters:
heplify -i bond0 -pr 5050-5090 -hs my.hep.server:9060 -hn SIPNT3 -d rtcp,rtp,sdp
2. Re provisioned docker containers from scratch
3. Read in a PCAP (that contained RTCP), but viewing it in Homer, there is no **RTCP or LOG** information whatsoever.
4. Re do the above after doing the below:
clear browser cache
sudo docker system prune
sudo docker volume prune
sudo docker-compose pull
sudo docker-compose up
5. Using: https://github.com/sipcapture/homer/wiki/Troubleshooting-Homer-7.7#debug-in-web-console to troubleshoot.

Not sure what else to check.

**Comment by adubovikov** [comment]
Sorry, but can you please tell us if you see any data in the QOS report for this call ? (web console)
Looks like it returns nothing.

**Comment by Sp0rN** [comment]
Dont have that original call anymore, but have another (the same call i worked with @negbie on):
QOS Report:

![image](https://user-images.githubusercontent.com/31306657/75786130-7db42d80-5d6d-11ea-9a23-19aefd0641dc.png)

Flow:
![image](https://user-images.githubusercontent.com/31306657/75786381-dc79a700-5d6d-11ea-959b-0cdef866754d.png)

**Comment by adubovikov** [comment]
Can you please check the payloadType in the your RTCP response ?

![Screenshot from 2020-03-03 16-57-44](https://user-images.githubusercontent.com/4513061/75793777-23689c00-5d70-11ea-8876-0af1019451c3.png)

**Comment by adubovikov** [comment]
@RFbkak37y3kIY looks like here is a parsing issue - the Simple view/View and Ports don't have sliders

**Comment by Sp0rN** [comment]
@adubovikov 

Excuse the naivety, how would i get check my PayloadType, not 100% from your screenshot.

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer/wiki/Troubleshooting-Homer-7.7#debug-in-web-console  
->  Network tab
and check the API qos query for this call

**Comment by adubovikov** [comment]
also, please check if you have any "parsing issues" in the console tab

**Comment by Sp0rN** [comment]
Thanks @adubovikov 
![image](https://user-images.githubusercontent.com/31306657/75800280-f8874380-5d81-11ea-8e09-8038c173cbb1.png)

Not finding any parsing issues, also double checked, im seeing the sliders in every call now (its  actually something I didnt see when posting that image)

**Comment by Sp0rN** [comment]
Any ideas yet? Not sure where else to look.

**Comment by adubovikov** [comment]
if you can share a dump of our rtcp from hep_proto_5 table (for this call id) we can check it more deeply. So far, no ideas. You can share your dump privately

**Comment by Sp0rN** [comment]
@adubovikov 

What would be the easiest way to get the dump  to you privately?

**Comment by adubovikov** [comment]
https://onetimesecret.com/secret/k77iq0htdzlmr5p12l3xv1j61qrbm5j

**Comment by adubovikov** [comment]
@Sp0rN 
https://onetimesecret.com/secret/h74x3in0s5tj4epcl8lwy0igo2kcr89

**Comment by Sp0rN** [comment]
https://onetimesecret.com/secret/omz95ozt6zlepot8ab8ujdw227cj7pl

Hope it formats properly.

**Comment by adubovikov** [comment]
this is one time :-) 
send me to alexandr.dubovikov_at_gmail

**Comment by Sp0rN** [comment]
@adubovikov 

Were you able to import the .psql i sent?

**Comment by adubovikov** [comment]
not yet.. sorry but we also have a job :-) please be patient

**Comment by Sp0rN** [comment]
@adubovikov 

Haha understood, I will wait for your feedback.

**Comment by adubovikov** [comment]
I have replied you. Your data displayes correct in the latest version of Homer UI and API. Please upgrade your docker to the latest and please be sure you didn't forget to clean up your caches.
I close the ticket.
