### ISSUE TITLE
Restricted user WebGUI setting - cosmetic issues

### ISSUE THREAD

**Issue by kpribic** [sipcapture/homer-ui#190]
When logging in as a user without admin privileges there are several minor cosmetic issues in WebGUI:

1. Under settings it says Admin settings, should be "User Settings"
2. Under settings it show "Users" option on the left that doesn't contain anything, probably should be removed.
3. Under setting it shows "Advanced" option on the left. Probably shouldn't show that to restricted users because there could be some information leaking due to parts of Json being shown.

![image](https://user-images.githubusercontent.com/50572561/77892205-8287d680-7272-11ea-8709-a1d4bf7916df.png)

**Comment by adubovikov** [comment]
1. Ok
2. It should show only one user (yourself)
3. this is doesn't matter because this information user should get, otherweise the grafana and another widgets (prometheus) will not work

**Comment by lmangani** [comment]
@kpribic about point 3) in defaults we use admin to access Grafana for demo purposes, but in a proper setup, this should be a "generic" read only user most likely. Up to the ingrator, we can't make this a preset since its really an optional, external component.

**Comment by kpribic** [comment]
> @kpribic about point 3) in defaults we use admin to access Grafana for demo purposes, but in a proper setup, this should be a "generic" read only user most likely. Up to the ingrator, we can't make this a preset since its really an optional, external component.

Ah, I didn't think that far, I just saw the word "password" and thought it could be an isse :-)

@adubovikov Regarding point 2) for some reason it doesn't show my user:
![image](https://user-images.githubusercontent.com/50572561/77894667-e069ed80-7275-11ea-869f-3f49fb48389a.png)

Although that could be due to my setup, I'm testing some LDAP changes, not sure if it will behave the same if it's only local accounts. I'll check.

**Comment by adubovikov** [comment]
because you use LDAP :-) If it will be internal AUTH, the user will be displayed.

**Comment by adubovikov** [comment]
need only change #1

**Comment by kpribic** [comment]
2) works well when I login with local accounts, I guess I messed something up when I fiddled with LDAP auth for restricted users...

**Comment by adubovikov** [comment]
fixed
