### ISSUE TITLE
Hardcoded time limits within transaction range causes dialogs to truncate in flow/export in long calls

### ISSUE THREAD

**Issue by rwilkinson87** [sipcapture/homer-ui#199]
It seems that there are some hardcoded time limits (5 mins before and 10 mins after) a packet resulting in packets within the same dialog, but outside of these times (for example a call lasting >10/15mins) will not show up in the Flow/Export view.

This means the flow/export view will only show the parts of the dialog -5minutes and +10 minutes before the selected packet.  Therefore, on long calls >15 minutes, the flow makes it look like the dialog was suddently interrupted or did not finish.

I would imagine expected behaviour is *all* packets from the dialog should be displayed in the flow; or at least ones within the dialog that are also within the time range seleted within the UI (and thus displayed in the main search container).

I'm not an Angular developer so unfortunately cannot offer much assistance, although I found references to these hardcoded limits in 

src/app/components/search-grid-call/search-grid-call.component.ts

lines 123 - 127
lines 243 - 252

I believe there is also a post started by someone else on the homer-app repo which is related.  Although this seems to be a UI issue as opposed to an API one

**Comment by adubovikov** [comment]
you can change these parameters in the mapping: 
```
 "lookup_range": [
            -300,
            200
        ]
```

**Comment by adubovikov** [comment]
![Screenshot from 2020-04-15 13-38-58](https://user-images.githubusercontent.com/4513061/79333258-81b39d80-7f1e-11ea-82ce-b29b5acaa799.png)

**Comment by yannickmcosta** [comment]
Very useful, thanks @adubovikov, Is there any completed documentation anywhere referencing all this? Seems to also be the case with other issues mentioned, including some on the /homer repo.

**Comment by adubovikov** [comment]
sorry guys, looks like at the end we use original timestamps. Let us fix it

**Comment by rwilkinson87** [comment]
Thanks @adubovikov I've set a wide range and has much improved my issue.  As @yannickmcosta mentioned is there a definitive documentation source anywhere that'll save opening unnecessary issue reports?

**Comment by adubovikov** [comment]
the good documentation is our weak point ;-) therefore we are looking for volunteers who can help us :-) anyway here is some description about correlation mappings: https://github.com/sipcapture/homer-app/issues/278

**Comment by adubovikov** [comment]
so, for the future, we have added the system param: 
https://github.com/sipcapture/homer-app/commit/875a65100b5189521429e320db57e7e8b5ad3cdc

search -> transaction
``` 
{
      "tabpositon": "flow", 
      "lookup_range": [-300, 200]
}
```
lookup_range =  first param for "from", second for "to" . The resolution is in seconds.

Please wait for the UI patch.
