### ISSUE TITLE
stats dashboards empty

### ISSUE THREAD

**Issue by nshopik** [sipcapture/homer-ui#2]
All stats dashboards are empty for me, just blanks. Others like Clock or RIPE DB Search working, but sometimes also fail with error `Could not resolve all promises`.

I did check that Mysql have all data in table `select * from sip_capture_call_20150619;`

**Comment by adubovikov** [comment]
you have to check if any data in the stats tables.

sorry, who generate "Could not resolve all promises" ? Search or RIPE ?

please make a screenshot.

**Comment by nshopik** [comment]
![image](https://cloud.githubusercontent.com/assets/4439311/8253566/e91f6cda-1699-11e5-9606-b5b788f86502.png)

stats_data, stats_ip, stats_method, stats_useragent all of them have data

**Comment by adubovikov** [comment]
ok, this is RIPE blocked you. They have rate limit per hours. Please remove this widget.

about stats, Please open chrome web debuger and press on reload of Packet Statistic and check the reply error. Maybe you don't have access to the stats DB ?

**Comment by nshopik** [comment]
I've already checked that via wireshark, it return 200 OK. 

But I found errors for Alerts API there is small type only work in virtualhost but not on sub-folder. I'll send patch for that.

I'm probably not finished configuration doc says `Configure Admin > Nodes to point to your MySQL instances w/ authentication` but I'm not really understand where is that? My profile or settings menu doesn't work only logout

**Comment by lmangani** [comment]
Nikolay,

Will check - You can of course also change those node access directly in
the configuration MySQL table if you need to do so.

Thanks for your continued input,

Lorenzo

**Comment by nshopik** [comment]
I found system admin dashboard but it doesn't work (changes not saved), so I've updated values via mysql but still can't any data. Is status value should be 1 for node to be active?

**Comment by nshopik** [comment]
Only warnning I found is `preg_match(): Compilation failed: unmatched parentheses at offset 8 in /var/www/homer5/api/RestService/Server.php on line 1198`

**Comment by lmangani** [comment]
Nikolay, are you still stuck at the same point?

**Comment by nshopik** [comment]
Yeah, I currently out of ideas how to get more debugging information I'm not that good at php.

**Comment by lmangani** [comment]
Seems a possible issue with database access if you cannot save. Could you open a case for this on the Homer-API tracker with replication details or drop us a mail at support@sipcapture.org to help out?

**Comment by adubovikov** [comment]
Nikolay,

sorry, Do you use nginx or apache ? If apache, did you activate AllowOverride All ? Looks like the mod_rewrite doesn't work.

Wbr,
Alexandr

**Comment by nshopik** [comment]
Yeah I'm on Apache, mod_rewrite enabled and `AllowOverride all` is set. This is same apache as I have for homer 3.6 with same config file.

**Comment by adubovikov** [comment]
can you give us ssh/web access ? If yes, please drop me a mail or contact me in gtalk

**Comment by nshopik** [comment]
@adubovikov Thanks 

This is fixed by this commit https://github.com/sipcapture/homer-api/commit/93120cece243e0e988039f8de76debcdc5520dc7
