### ISSUE TITLE
Horizontal scrollbar decouples vertical lines from hostnames

### ISSUE THREAD

**Issue by kpribic** [sipcapture/homer-ui#223]
When the flow window is small enough (or trace is big enough) so that not all hostnames fit in the flow window then horizontal scroll bar appears. However when that scroll bar is used hostname boxes on the top of the flow don't pan in sync with vertical lines.

In this example below it is noticable that vertical lines are no longer aligned because I scrolled a bit to the right:

![image](https://user-images.githubusercontent.com/50572561/81705297-303ff500-946f-11ea-9a5d-f756d409465b.png)

**Comment by jacovinus** [comment]
Solved on Devel branch.
