### ISSUE TITLE
Does Homer-UI import homer-view?

### ISSUE THREAD

**Issue by systemcrash** [sipcapture/homer-ui#226]
https://github.com/sipcapture/homer-ui/blob/214252f313c68c510bd365b38f1eefbe0f4037fb/src/app/components/search-grid-call/detail-dialog/tab-flow/tab-flow.component.ts#L114

Or does this need fixing as well?

**Comment by systemcrash** [comment]
https://github.com/sipcapture/homer-view/pull/17

**Comment by adubovikov** [comment]
yes, it should be or IP:PORT or [IP]:PORT

**Comment by systemcrash** [comment]
Yes what?

**Comment by adubovikov** [comment]
> Yes what?

sorry ?

**Comment by systemcrash** [comment]
Does Homer-UI import homer-view?

**Comment by adubovikov** [comment]
no, these are two separate projects

**Comment by systemcrash** [comment]
OK - But... does this get imported into homer-app?

**Comment by systemcrash** [comment]
jfc. OK whatevs. Here's a fix. 

https://github.com/sipcapture/homer-ui/pull/227

**Comment by lmangani** [comment]
To further clarify - Homer does NOT import HOMER-View. The two are independent from each to allow customization and integration specifically without putting roadblockers to our ideas or causing instabilities.

**Comment by systemcrash** [comment]
OK - thank you. Good to know. Seemed like a lot of duplication.

**Comment by lmangani** [comment]
It's not duplication as internally they feed the same logic and code, but there is an intentional separation of intents. Many just want to integrate a part of HOMER in their portal and its easier to derive it from this project rather than from the assembled UI.
