### ISSUE TITLE
Full IPv6 addr in graph partially hidden/obliterated

### ISSUE THREAD

**Issue by systemcrash** [sipcapture/homer-ui#231]
Looks like

![Screenshot 2020-05-18 at 14 25 53](https://user-images.githubusercontent.com/647633/82213081-e09c7600-9913-11ea-8e66-b47f32b9dede.png)

One potential, not-ideal solution (read: workaround) is to limit the length of the displayed IPv6 by omitting some IPv6 addr block quads with `...` e.g. `fe80:...:5678`

Better solution is to place the next vertical line on the graph after the end of the IPv6. ( This is another problem if vertical lines are equally spaced )

**Comment by systemcrash** [comment]
This seems to be down to how the window tries to draw all elements in a single graph (without having a reasonable, comfortable assumption of window width). In my graph with 8 endpoints, it tries to jam them all in, no horizontal scrolling...

**Comment by lmangani** [comment]
@systemcrash we've changed things around a bit to improve this, should have a release soonish

**Comment by jacovinus** [comment]
@systemcrash can you confirm your operative system and browser for this issue? That will help us with testing before release.

**Comment by systemcrash** [comment]
I run a mix of browsers (chrome, ff, safari) on macOS.

**Comment by adubovikov** [comment]
And in all browserd you have same result?

**Comment by mikegoodstadt** [comment]
Fixed in commit: [fix: IPv6 with Combine Aliases & Show/hide ports](https://github.com/sipcapture/homer-ui/commit/2ac1f748e93828f7d2f8b7c24d61355dad8d9402)

**Comment by systemcrash** [comment]
Interesting fix! A little feedback on the latest fix:

-IP addr is partially hidden up top if name spans two rows
-can no longer select IP to copy/paste (occasionally useful)

IPv4

![Screenshot 2020-06-24 at 01 58 48](https://user-images.githubusercontent.com/647633/85479876-4c32cc80-b5bf-11ea-88a3-3942b941a352.png)

IPv6 (alias spans two rows, so IPv6 is partially hidden)

Also cannot select/copy. But hover-over to show full v6 is nice. 

![Screenshot 2020-06-24 at 02 07 59](https://user-images.githubusercontent.com/647633/85480163-ca8f6e80-b5bf-11ea-9e5a-aab243e1ccb4.png)

**Comment by systemcrash** [comment]
Also, debug console is flooded with errors if I disable and enable "combined by alias" option. 

Two columns. Turn off. I get multiple columns. OK so far. Try to turn on. Still have multiple columns. Something wrong.

**Comment by systemcrash** [comment]
Would just like to point out that copy/paste is v useful, esp since we get new endpoints popping up now and then, and the graph is a convenient place to grab the address.

**Comment by systemcrash** [comment]
Also, not sure what it depends on, but sometimes the message details tab is completely empty. :( 

![Screenshot 2020-06-24 at 02 23 45](https://user-images.githubusercontent.com/647633/85481478-29ee7e00-b5c2-11ea-9a5a-b59da2cfd541.png)

For a busy multi-hop call when the graph gets a bit crowded after turning off "combined by alias" - arrows to and from some hops look a bit jumbled now. :/ 

![Screenshot 2020-06-24 at 02 27 27](https://user-images.githubusercontent.com/647633/85482032-3de6af80-b5c3-11ea-99b3-553ddb8061ae.png)


Summary: things look better, sharper. Fix needs a bit more polish.

**Comment by systemcrash** [comment]
Exported graphs don't seem to fare much better:

![b0cee0dcd15a1b103388e628eebf856a@sipgt-4a69c29a](https://user-images.githubusercontent.com/647633/85482865-0b898200-b5c4-11ea-8984-df9b6fbe3638.png)

**Comment by systemcrash** [comment]
Hmm, stuff like this should not happen, however:

Two different addresses in the same subnet get coalesced into a single hop...? .2 and .21 are two *very* different systems. 

![Screenshot 2020-06-24 at 02 43 14](https://user-images.githubusercontent.com/647633/85483443-155fb500-b5c5-11ea-8fd2-1a17360d18a4.png)


This seems to be because IPs are matched as strings, instead of converted to an integer and then compared.

**Comment by systemcrash** [comment]
Also - turn "show ports" off - ports show. Turn "show ports" on, ports hidden.... opposite 🤕

**Comment by mikegoodstadt** [comment]
Thanks for all these - we will go through them now.

**Comment by mikegoodstadt** [comment]
Hi again - can you try purging the cache. The Show ports toggle should be fixed but may need the cache to be clean to see it. This may also sort other items but we are checking them.

**Comment by systemcrash** [comment]
I tried. Purged cache. No help. The first toggle of 'port' does nothing - performs no action. Its behaviour then acts 'inverted'. All other bugs the same. 

I've rolled back the Docker image now...

**Comment by systemcrash** [comment]
A suggestion: if we're merging same hosts now, please expand the IPv6 to full IP, since we have so much screen real-estate when graphs are only two or three hops.
