### ISSUE TITLE
Sort by src/dst IP does not work as expected in search results

### ISSUE THREAD

**Issue by systemcrash** [sipcapture/homer-ui#240]
( I assume this problem belongs here, and not in homer-app )

It seems to be doing a trivial text string based sort, rather than an IP based sort ( by blocks in the IP )

e.g. sorting by increasing results in:
```
122. ....
193. ....
52. ....
89. ...
```

**Comment by systemcrash** [comment]
This https://github.com/indutny/node-ip may help. It handles IPv6 correctly...

PGsql also has built-ins for sorting IPs. Not an option, I don't think, since, most data is stored in JSON.  Needs sorting at user endpoint.

**Comment by adubovikov** [comment]
because the IP presents here as a string and not as integer, therefore I dont think we can do something here

**Comment by adubovikov** [comment]
old ticket and was fixed already

**Comment by systemcrash** [comment]
OK, the way things work is 'good enough' - the problem here is it's a text sort (vs int sort). The text sort does not behave as expected, and means that the IP I'm looking for might be a few pages further on in results. Is adding a 'hidden' column (or two) to search results, of the int (or long) version of the IP a big (t)ask? 

I tried sorting on the latest master and text sort of IPs still behaves the same as ever.
