### ISSUE TITLE
Call-Flow graph in 5.x version didnt show "call duration" any more on top

### ISSUE THREAD

**Issue by khorsmann** [sipcapture/homer-ui#25]
Hello,

i miss a nice information in the call-flow graph - the call duration.

New homer 5.x without duration :-(
![image](https://cloud.githubusercontent.com/assets/5255309/9525215/4e326e0e-4ce3-11e5-9bc5-c9b88b9697a1.png)

old homer 3.x with duration
![image](https://cloud.githubusercontent.com/assets/5255309/9525303/c8c496ce-4ce3-11e5-90d8-0244fb46f519.png)

**Comment by adubovikov** [comment]
Feel free to implement the feature and commit it.
We are open for all contributions to the project.

**Comment by michaelarnauts** [comment]
I assume this is to be changed in homerCflow.min.js, but where can I find the original version of the file (not minimized)?

**Comment by adubovikov** [comment]
Michael, do you want to implement this ?

**Comment by michaelarnauts** [comment]
I'm running Homer 3.5 currently, and want to move over to 5, so I'm going over all the issues that are currently holding me back from switching over.

If the changes are not to complex, I'm willing to take a look.

I assume I have to find the 200 OK and the BYE and calculate the time difference between these two? I don't know about the code in Homer 5, but if this information is available, it should be quite easy to implement, not?

**Comment by lmangani** [comment]
Code from 3.5 can be adapted for this, effectively storing the max/min timestamp across all methods returned for a session, ie:
$totalduration = gmdate("H:i:s", intval(($max_ts- $min_ts) / 1000000));

**Comment by lmangani** [comment]
Implemented in dev branch alongside many updates to session view, will push soon

**Comment by lmangani** [comment]
Implemented in 85ed5cbdb6d905d6f367060009a78dc27719dea8 alongside other things - feedback welcome
