### ISSUE TITLE
Set a default transaction for search

### ISSUE THREAD

**Issue by michaelarnauts** [sipcapture/homer-ui#28]
When doing a search without specifying the transaction (CALLS, REGISTRATION or OTHER), no results are shown. In homer 3.5, when you didn't select anything, the system searched for everything.

There seems to be no way to specify a default transaction. Having a default transaction for searching allows us to simplify the search form even more, skipping the requirement for users to always specify it.

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-api/commit/4779310e99306bd04c9cfea191b87fcd25078fcc
