### ISSUE TITLE
Details not shown in flow window - Homer 7

### ISSUE THREAD

**Issue by kYroL01** [sipcapture/homer-ui#282]
I found a bug in Homer `7.7.034` . 
Those are the steps to reproduce the issue

1. Open the call
2. Click on one message (i.e. INVITE)
3. Check details -> **Shown**
4. Close tab
5. Reopen INVITE
5. Check details -> **Empty**

![flow](https://user-images.githubusercontent.com/7222956/85584935-e0dd0f00-b63f-11ea-88e6-a433c4aa6117.png)

**Comment by jacovinus** [comment]
@kYroL01   I see on #282 that you have the previous version of Homer there. Were you able to update it to the [Last release](https://github.com/sipcapture/homer-ui/releases/tag/7.8.0)?

**Comment by mikegoodstadt** [comment]
Fixed in #295
