### ISSUE TITLE
Payload type filter: not working when there's only 1 payload type

### ISSUE THREAD

**Issue by AlexeyOplachko** [sipcapture/homer-ui#288]
Deselecting a single/lone payload type in Flow graph filters produces errors in the console.
Errors indicate missing data needed for graph to generate, therefore no graph is displayed.
When payload type is re-selected, Flow graph is correctly restored.
Filtering a single/lone type is redundant - propose disabling checkbox in this case.

**Comment by adubovikov** [comment]
old one. Should be closed
