### ISSUE TITLE
Expand IPv6 in Flow when width permits.

### ISSUE THREAD

**Issue by mikegoodstadt** [sipcapture/homer-ui#293]
Merging same hosts expands the IPv6 to full IP when graphs are only two or three hops.
Requested in [#231](https://github.com/sipcapture/homer-ui/issues/231#issuecomment-648833465)

**Comment by systemcrash** [comment]
I guess this is more tricky than it seems - taking into account window width is one possible factor, which may be disregarded when exporting to e.g. PNG. 

Two approaches: 
-expand IPv6 when width permits
-shrinking IPv6 when width lacks

'two or three' seems safe - keep in mind that some (I/me) actually log in via a mobile browser (now that it's finally possible to do so) so viewing from such UAs should be considered. So including total (available) window width in a calculation seems quite relevant now.

**Comment by adubovikov** [comment]
i think it was fixed already. Please reopen if needed
