### ISSUE TITLE
Different addresses in the same subnet get combined.

### ISSUE THREAD

**Issue by mikegoodstadt** [sipcapture/homer-ui#294]
Reported in [#231](https://github.com/sipcapture/homer-ui/issues/231#issuecomment-648517686) :  Different addresses (eg. .2 and .21) in the same subnet get coalesced into a single hop.
@systemcrash From your screenshot they are in the same alias. I apologise if I have misunderstood. Can you give details to help us reproduce this?

![](https://user-images.githubusercontent.com/647633/85483443-155fb500-b5c5-11ea-8fd2-1a17360d18a4.png)

**Comment by systemcrash** [comment]
Traffic in image above (*.2 <-> *.21) is between entry 1 and 3 in image below. Two unique endpoints. 

![Screenshot 2020-07-02 at 23 28 56](https://user-images.githubusercontent.com/647633/86411050-43778000-bcbc-11ea-96f8-8cfa56e418ce.png)

Smells like address string anchoring ( use of `$` to mark end of string )

**Comment by mikegoodstadt** [comment]
Tested ok for IPv4.
Now testing for IPv6.

**Comment by jacovinus** [comment]
closing, solved for IPV4 on https://github.com/sipcapture/homer-ui/commit/4d6128c5cf78584f10f7f0f2f88c50df131d8acc

**Comment by systemcrash** [comment]
> closing, solved for IPV4 on [4d6128c](https://github.com/sipcapture/homer-ui/commit/4d6128c5cf78584f10f7f0f2f88c50df131d8acc)


Is this in current builds of homer? Or waiting for other PRs before go-live? I just pulled current homer-webapp and... still observing this behaviour.
