### ISSUE TITLE
 Default dashboard for users in case they login through LDAP

### ISSUE THREAD

**Issue by mikegoodstadt** [sipcapture/homer-ui#296]
Dashboard settings are saved by user. When no such user exists, as in the case of a login through LDAP, the dashboards are not saved.
Requires investigation into logical user-facing solutions.

**Comment by adubovikov** [comment]
@mikegoodstadt in case of LDAP we create a fake object and do insertion to the settings DB, after that user can save/delete/edit

**Comment by mikegoodstadt** [comment]
Ok Thanks
