### ISSUE TITLE
LOG 100 doesn't show raw data in 7.8.1

### ISSUE THREAD

**Issue by kpribic** [sipcapture/homer-ui#304]
7.8.1 breaks display of raw logs (at least for my scenario). Same LOG message 62201 from the same DB shown in newer and older HomerUI (tried with homer-app 1.1.37 and 1.2.1 with same results):
![image](https://user-images.githubusercontent.com/50572561/88379163-b4352800-cda2-11ea-84b3-3f7fff166cf2.png)

Chrome console (Version 83.0.4103.116 (Official Build) (64-bit)) doesn't show any errors.
Network log in chrome shows a proper query for message 62201 and a response that contains proper RAW. It just gets misplaced somewhere before it's show on the UI. This is response after json pretty plugin in sublime:
![image](https://user-images.githubusercontent.com/50572561/88379292-f5c5d300-cda2-11ea-974b-6357867bcff5.png)

**Comment by lmangani** [comment]
@kpribic thanks for the report
@mikegoodstadt could you have the team validate and hotpatch if confirmed?

**Comment by mikegoodstadt** [comment]
@kpribic I am trying to replicate this. Can you send the PCAP for your example call? Thanks!

**Comment by adubovikov** [comment]
we can confirm the issue. The dev-team is working on it

**Comment by kpribic** [comment]
@mikegoodstadt This fix unfortunately doesn't work for me. I just tested with devel branch, and it still displays "raw is empty" while still managing to output the snipped above the arrow.

![image](https://user-images.githubusercontent.com/50572561/89521383-adb1a200-d7df-11ea-9234-642935628762.png)
