### ISSUE TITLE
Missing one way rtcp in qos tab

### ISSUE THREAD

**Issue by byphone** [sipcapture/homer-ui#309]
Hello everybody

Using last version for all components. I check the hep_proto_5_default, and i have for the same SID 11 rows with rtcp stats, 9 for one way (freeswitch emitting rtcp stats every 5s) and 2 from my voip provider (one when audio stream begins, and the other when it stops). 

I check the qos query and i can see that server send to browser the 11 rows shown in the database.

In the QOS tab, i can only see one way with 9 rtcp stats, missing the other way....

In the console tab, i've just "no agent subscription object found for type [cdr]"

Any idea ?

**Comment by lmangani** [comment]
@AlexeyOplachko best to request a db export in this case rather than a PCAP to replicate

**Comment by AlexeyOplachko** [comment]
I'll remember for next time, but anyways this is probably fixed(assuming it's same problem as that issue I mentioned earlier) with last PR to dev-branch.

**Comment by mikegoodstadt** [comment]
@byphone Hi - were you able to test if the fix in the devel branch solved your issue?

**Comment by adubovikov** [comment]
please take the last release and retest
