### ISSUE TITLE
Agentsub delete doesn't work

### ISSUE THREAD

**Issue by kpribic** [sipcapture/homer-ui#313]
![image](https://user-images.githubusercontent.com/50572561/89296369-87b2c300-d662-11ea-9cde-7fbd12f03251.png)

Tested on Homer-ui 7.8.0 and 7.7.0.34.

**Comment by adubovikov** [comment]
confirmed. The API sends undefined and not uuid

**Comment by adubovikov** [comment]
thank you for the fix

**Comment by jacovinus** [comment]
@kpribic solved by @AlexeyOplachko, please pull from Devel branch and confirm if solved your issue. Many thanks.

**Comment by kpribic** [comment]
Appears to work OK.
