### ISSUE TITLE
Missing image file

### ISSUE THREAD

**Issue by Homer-Rivera** [sipcapture/homer-ui#32]
When trying to view the export link when viewing a call I see an error that the following image is missing.

http://homer.example.com/share/img/gateways/sipgateway.jpg

**Comment by andycol** [comment]
missing configuration.php file

**Comment by lmangani** [comment]
sorry for the late reply, this is due to the relative nature of the callflow link, will be fixed shortly

**Comment by lmangani** [comment]
Fixed - please update  your API/UI and feel free to reopen this issue if needed
