### ISSUE TITLE
Grafana Integration & Widgets

### ISSUE THREAD

**Issue by lmangani** [sipcapture/homer-ui#328]
There are a few core issues with the Grafana Integration:

Grafana Widget:

- by default it should time should be `Dashboard`
- by default the link gets populated with the wrong URL from the grafana advanced config. Setting it empty makes it work.
- when empty of settings/data the widget iframe somehow loads/display HOMER. Should not be the case.

Grafana as iFrame Panel:

- when including Grafana as an iFrame it seems no longer possible to switch dashboards/panels
- the dashboard frame is not syncronized with the iFrame URL by default.

@AlexeyOplachko could you kindly address, check and test the above when possible?

**Comment by adubovikov** [comment]
fixed in devel https://github.com/sipcapture/homer-ui/commit/28f34367a165b292e00f0f17ea204efc8bb1c668

**Comment by adubovikov** [comment]
the version 1.3.0 has been released. Please install it and retest it.

**Comment by AlexeyOplachko** [comment]
Should be completely fixed with https://github.com/sipcapture/homer-ui/commit/f648fabfb7a0969efd04f6011fbe229975728111
