### ISSUE TITLE
Unable to see call flow.  Can see call-flow on shared URL

### ISSUE THREAD

**Issue by Homer-Rivera** [sipcapture/homer-ui#33]
When I am looking at a call graph and I click on a method like invite the new modal opens with no data.

In chrome I see this error.

TypeError: Cannot read property 'id' of undefined
    at dialogCtrl.js:73
    at I (angular.js:11446)
    at angular.js:11532
    at k.$eval (angular.js:12556)
    at k.$digest (angular.js:12368)
    at k.$apply (angular.js:12660)
    at h (angular.js:8272)
    at x (angular.js:8477)
    at XMLHttpRequest.z.onreadystatechange (angular.js:8416)

But If I open the link from the export tabs shared link URL I can see the call-flow.

Am I missing something?

No info for message or details
![homer-ui-message-1](https://cloud.githubusercontent.com/assets/8550715/10554312/29fb9654-7417-11e5-9398-30d7bb14a67d.PNG)

Works if I use the share URL

![homer-ui-message-2](https://cloud.githubusercontent.com/assets/8550715/10554329/4d06ce52-7417-11e5-8f47-d3f006b3bb34.PNG)

**Comment by lmangani** [comment]
Hi,

Make sure your capture server and agent are NTP synchronized. It seems they might be slightly off at this time, please check and confirm if this is the case.

**Comment by Homer-Rivera** [comment]
That would be it.  My times were not synced.  All is well.

Thanks!
