### ISSUE TITLE
broken PCAP files for IPv6 payload

### ISSUE THREAD

**Issue by sergey-safarov** [sipcapture/homer-ui#377]
When I try to export SIP dialog into PCAP file where I used IPv6 endpoints, then I get broken PCAP files.
Example attached

[HOMER5-44.230.120.20-_98-12_12_2020 13_52_50.pcap.gz](https://github.com/sipcapture/homer-ui/files/5682923/HOMER5-44.230.120.20-_98-12_12_2020.13_52_50.pcap.gz)

**Comment by adubovikov** [comment]
It has been fixed. Please install the latest version of homer-app and test again.

**Comment by sergey-safarov** [comment]
Just tested docker image `sipcapture/webapp` that build 9 hours ago.
PCAP exported and opened properly.
But PCAP does not contain any messages between IPv6 nodes.

**Comment by adubovikov** [comment]
Fixed here. https://github.com/sipcapture/homer-app/commit/64501b5a43bacc7a5bf56763861be28aaf19e9df

let me build a new release

**Comment by adubovikov** [comment]
homer-app-1.4.13. Please recheck.

**Comment by sergey-safarov** [comment]
Hello Alexandr @adubovikov
Just tested the latest docker images.
Now messages between IPv6 hosts are exported properly.

**Comment by adubovikov** [comment]
@sergey-safarov super, please give us a star here -> https://github.com/sipcapture/homer/stargazers

**Comment by sergey-safarov** [comment]
I added stars to the `homer`, `homer-app` and `heplify-server` projects.
