### ISSUE TITLE
Add success / failure advice on pcap import widget

### ISSUE THREAD

**Issue by jacovinus** [sipcapture/homer-ui#383]
Add a success or failure advice on import PCAP widget for user to ACK easily of data transfer result. 
Actually only way to see it is at console or at network tab on browser.

**Comment by adubovikov** [comment]
@jacovinus any progress here ?

**Comment by jacovinus** [comment]
closing since my version of the widget wont be used (replaced by the @RFbkak37y3kIY 's one and solved)
