### ISSUE TITLE
Invalid character in db causing blank QoS page

### ISSUE THREAD

**Issue by sunilmmore** [sipcapture/homer-ui#384]
Hello I am using RTPENGINE Version: 9.1.1.2+0~mr9.1.1.2 and trying to connect with homer 7 . The QOS page in homer could not load up. Upon inspection I could observe that the statistics are sent to homer. However the sdes_information type 8 has a text value {"sdes_chunk_ssrc":3191907923,"type":8,"text":".x-rtp-session-idB9166F4F7DDA430584831CDB41C09BD5"} when sent to homer. What goes into the db is
{"sdes_chunk_ssrc":3191907923,"type":8,"text":"�x-rtp-session-idB9166F4F7DDA430584831CDB41C09BD5
which later makes the json invalid. After manually editing the value and removing the invalid character from db, I could get the QOS page.
below are a few more details

data sent to homer by rtpengine.
{ "sender_information":{"ntp_timestamp_sec":3818986922,"ntp_timestamp_usec":1687922147,"octets":29584,"rtp_timestamp":2840360, "packets":172},"ssrc":3191907923,"type":200,"report_count":1,"report_blocks":[{"source_ssrc":47986343,"highest_seq_no":39887,"fraction_lost":0,"ia_jitter":114,"packets_lost":0,"lsr":0,"dlsr":0}],"sdes_report_count":1,"sdes_information": [ {"sdes_chunk_ssrc":3191907923,"type":1,"text":"6F34204489AE4BB09E80D6356EE7CBB3@unique.zB7EA455E93BC46D1.org"},{"sdes_chunk_ssrc":3191907923,"type":8,"text":".x-rtp-session-idB9166F4F7DDA430584831CDB41C09BD5"}] }
value in db
{ "sender_information":{"ntp_timestamp_sec":3818986922,"ntp_timestamp_usec":1687922147,"octets":29584,"rtp_timestamp":2840360, "packets":172},"ssrc":3191907923,"type":200,"report_count":1,"report_blocks":[{"source_ssrc":47986343,"highest_seq_no":39887,"fraction_lost":0,"ia_jitter":114,"packets_lost":0,"lsr":0,"dlsr":0}],"sdes_report_count":1,"sdes_information": [ {"sdes_chunk_ssrc":3191907923,"type":1,"text":"6F34204489AE4BB09E80D6356EE7CBB3@unique.zB7EA455E93BC46D1.org"},{"sdes_chunk_ssrc":3191907923,"type":8,"text":"�x-rtp-session-idB9166F4F7DDA430584831CDB41C09BD5"}] }

**Comment by adubovikov** [comment]
@sunilmmore can you please provide the JSON response that you received from API server ?

**Comment by sunilmmore** [comment]
@adubovikov I changed the old data to validate . Here's a new query response.


`{"rtcp":{"data":[{"captureId":"2099","correlation_id":"MjYwNmIwNDQyMTI5N2ZlZDkyNzkxNDY3YmM4ZDBmZmE.","create_date":"2021-01-07T07:37:17.362532Z","dbnode":"local","dstIp":"203.153.53.140","dstPort":50095,"id":68,"node":["2099","local"],"payloadType":5,"profile":"","proto":"rtcp","protocol":17,"protocolFamily":2,"raw":"{ \"ssrc\":2571351459,\"type\":201,\"report_count\":0,\"report_blocks\":[],\"sdes_report_count\":1,\"sdes_information\": [ {\"sdes_chunk_ssrc\":2571351459,\"type\":1,\"text\":\"6F34204489AE4BB09E80D6356EE7CBB3@unique.zB7EA455E93BC46D1.org\"},{\"sdes_chunk_ssrc\":2571351459,\"type\":8,\"text\":\"\u0010x-rtp-session-id0BAD9E87788B420A9E1F74928434C64C\"}] }","sid":"MjYwNmIwNDQyMTI5N2ZlZDkyNzkxNDY3YmM4ZDBmZmE.","srcIp":"203.153.53.157","srcPort":18193,"timeSeconds":1610005037,"timeUseconds":362532},{"captureId":"2099","correlation_id":"MjYwNmIwNDQyMTI5N2ZlZDkyNzkxNDY3YmM4ZDBmZmE.","create_date":"2021-01-07T07:37:20.37599Z","dbnode":"local","dstIp":"203.153.53.140","dstPort":50095,"id":69,"node":["local","2099"],"payloadType":5,"profile":"","proto":"rtcp","protocol":17,"protocolFamily":2,"raw":"{ \"sender_information\":{\"ntp_timestamp_sec\":3818993841,\"ntp_timestamp_usec\":807453852,\"octets\":25800,\"rtp_timestamp\":2398040, \"packets\":150},\"ssrc\":2571351459,\"type\":200,\"report_count\":1,\"report_blocks\":[{\"source_ssrc\":96552961,\"highest_seq_no\":13893,\"fraction_lost\":0,\"ia_jitter\":17,\"packets_lost\":0,\"lsr\":0,\"dlsr\":0}],\"sdes_report_count\":1,\"sdes_information\": [ {\"sdes_chunk_ssrc\":2571351459,\"type\":1,\"text\":\"6F34204489AE4BB09E80D6356EE7CBB3@unique.zB7EA455E93BC46D1.org\"},{\"sdes_chunk_ssrc\":2571351459,\"type\":8,\"text\":\"\u0010x-rtp-session-id0BAD9E87788B420A9E1F74928434C64C\"}] }","sid":"MjYwNmIwNDQyMTI5N2ZlZDkyNzkxNDY3YmM4ZDBmZmE.","srcIp":"203.153.53.157","srcPort":18193,"timeSeconds":1610005040,"timeUseconds":375990},{"captureId":"2099","correlation_id":"MjYwNmIwNDQyMTI5N2ZlZDkyNzkxNDY3YmM4ZDBmZmE.","create_date":"2021-01-07T07:37:23.386332Z","dbnode":"local","dstIp":"203.153.53.140","dstPort":50095,"id":70,"node":["local","2099"],"payloadType":5,"profile":"","proto":"rtcp","protocol":17,"protocolFamily":2,"raw":"{ \"sender_information\":{\"ntp_timestamp_sec\":3818993844,\"ntp_timestamp_usec\":893353198,\"octets\":51772,\"rtp_timestamp\":2422200, \"packets\":301},\"ssrc\":2571351459,\"type\":200,\"report_count\":1,\"report_blocks\":[{\"source_ssrc\":96552961,\"highest_seq_no\":14044,\"fraction_lost\":0,\"ia_jitter\":15,\"packets_lost\":0,\"lsr\":0,\"dlsr\":0}],\"sdes_report_count\":1,\"sdes_information\": [ {\"sdes_chunk_ssrc\":2571351459,\"type\":1,\"text\":\"6F34204489AE4BB09E80D6356EE7CBB3@unique.zB7EA455E93BC46D1.org\"},{\"sdes_chunk_ssrc\":2571351459,\"type\":8,\"text\":\"\u0010x-rtp-session-id0BAD9E87788B420A9E1F74928434C64C\"}] }","sid":"MjYwNmIwNDQyMTI5N2ZlZDkyNzkxNDY3YmM4ZDBmZmE.","srcIp":"203.153.53.157","srcPort":18193,"timeSeconds":1610005043,"timeUseconds":386332},{"captureId":"2099","correlation_id":"MjYwNmIwNDQyMTI5N2ZlZDkyNzkxNDY3YmM4ZDBmZmE.","create_date":"2021-01-07T07:37:26.400473Z","dbnode":"local","dstIp":"203.153.53.140","dstPort":50095,"id":71,"node":["2099","local"],"payloadType":5,"profile":"","proto":"rtcp","protocol":17,"protocolFamily":2,"raw":"{ \"sender_information\":{\"ntp_timestamp_sec\":3818993847,\"ntp_timestamp_usec\":893353198,\"octets\":77572,\"rtp_timestamp\":2446200, \"packets\":451},\"ssrc\":2571351459,\"type\":200,\"report_count\":1,\"report_blocks\":[{\"source_ssrc\":96552961,\"highest_seq_no\":14194,\"fraction_lost\":0,\"ia_jitter\":29,\"packets_lost\":0,\"lsr\":0,\"dlsr\":0}],\"sdes_report_count\":1,\"sdes_information\": [ {\"sdes_chunk_ssrc\":2571351459,\"type\":1,\"text\":\"6F34204489AE4BB09E80D6356EE7CBB3@unique.zB7EA455E93BC46D1.org\"},{\"sdes_chunk_ssrc\":2571351459,\"type\":8,\"text\":\"\u0010x-rtp-session-id0BAD9E87788B420A9E1F74928434C64C\"}] }","sid":"MjYwNmIwNDQyMTI5N2ZlZDkyNzkxNDY3YmM4ZDBmZmE.","srcIp":"203.153.53.157","srcPort":18193,"timeSeconds":1610005046,"timeUseconds":400473},{"captureId":"2099","correlation_id":"MjYwNmIwNDQyMTI5N2ZlZDkyNzkxNDY3YmM4ZDBmZmE.","create_date":"2021-01-07T07:37:29.411661Z","dbnode":"local","dstIp":"203.153.53.140","dstPort":50095,"id":72,"node":["local","2099"],"payloadType":5,"profile":"","proto":"rtcp","protocol":17,"protocolFamily":2,"raw":"{ \"sender_information\":{\"ntp_timestamp_sec\":3818993850,\"ntp_timestamp_usec\":979252543,\"octets\":103544,\"rtp_timestamp\":2470360, \"packets\":602},\"ssrc\":2571351459,\"type\":200,\"report_count\":1,\"report_blocks\":[{\"source_ssrc\":96552961,\"highest_seq_no\":14345,\"fraction_lost\":0,\"ia_jitter\":15,\"packets_lost\":0,\"lsr\":0,\"dlsr\":0}],\"sdes_report_count\":1,\"sdes_information\": [ {\"sdes_chunk_ssrc\":2571351459,\"type\":1,\"text\":\"6F34204489AE4BB09E80D6356EE7CBB3@unique.zB7EA455E93BC46D1.org\"},{\"sdes_chunk_ssrc\":2571351459,\"type\":8,\"text\":\"\u0010x-rtp-session-id0BAD9E87788B420A9E1F74928434C64C\"}] }","sid":"MjYwNmIwNDQyMTI5N2ZlZDkyNzkxNDY3YmM4ZDBmZmE.","srcIp":"203.153.53.157","srcPort":18193,"timeSeconds":1610005049,"timeUseconds":411661},{"captureId":"2099","correlation_id":"MjYwNmIwNDQyMTI5N2ZlZDkyNzkxNDY3YmM4ZDBmZmE.","create_date":"2021-01-07T07:37:32.420947Z","dbnode":"local","dstIp":"203.153.53.140","dstPort":50095,"id":73,"node":["local","2099"],"payloadType":5,"profile":"","proto":"rtcp","protocol":17,"protocolFamily":2,"raw":"{ \"sender_information\":{\"ntp_timestamp_sec\":3818993853,\"ntp_timestamp_usec\":1069446857,\"octets\":129516,\"rtp_timestamp\":2494520, \"packets\":753},\"ssrc\":2571351459,\"type\":200,\"report_count\":1,\"report_blocks\":[{\"source_ssrc\":96552961,\"highest_seq_no\":14495,\"fraction_lost\":0,\"ia_jitter\":18,\"packets_lost\":0,\"lsr\":0,\"dlsr\":0}],\"sdes_report_count\":1,\"sdes_information\": [ {\"sdes_chunk_ssrc\":2571351459,\"type\":1,\"text\":\"6F34204489AE4BB09E80D6356EE7CBB3@unique.zB7EA455E93BC46D1.org\"},{\"sdes_chunk_ssrc\":2571351459,\"type\":8,\"text\":\"\u0010x-rtp-session-id0BAD9E87788B420A9E1F74928434C64C\"}] }","sid":"MjYwNmIwNDQyMTI5N2ZlZDkyNzkxNDY3YmM4ZDBmZmE.","srcIp":"203.153.53.157","srcPort":18193,"timeSeconds":1610005052,"timeUseconds":420947},{"captureId":"2099","correlation_id":"MjYwNmIwNDQyMTI5N2ZlZDkyNzkxNDY3YmM4ZDBmZmE.","create_date":"2021-01-07T07:37:35.431396Z","dbnode":"local","dstIp":"203.153.53.140","dstPort":50095,"id":74,"node":["2099","local"],"payloadType":5,"profile":"","proto":"rtcp","protocol":17,"protocolFamily":2,"raw":"{ \"sender_information\":{\"ntp_timestamp_sec\":3818993856,\"ntp_timestamp_usec\":1065151889,\"octets\":155316,\"rtp_timestamp\":2518520, \"packets\":903},\"ssrc\":2571351459,\"type\":200,\"report_count\":1,\"report_blocks\":[{\"source_ssrc\":96552961,\"highest_seq_no\":14646,\"fraction_lost\":0,\"ia_jitter\":15,\"packets_lost\":0,\"lsr\":0,\"dlsr\":0}],\"sdes_report_count\":1,\"sdes_information\": [ {\"sdes_chunk_ssrc\":2571351459,\"type\":1,\"text\":\"6F34204489AE4BB09E80D6356EE7CBB3@unique.zB7EA455E93BC46D1.org\"},{\"sdes_chunk_ssrc\":2571351459,\"type\":8,\"text\":\"\u0010x-rtp-session-id0BAD9E87788B420A9E1F74928434C64C\"}] }","sid":"MjYwNmIwNDQyMTI5N2ZlZDkyNzkxNDY3YmM4ZDBmZmE.","srcIp":"203.153.53.157","srcPort":18193,"timeSeconds":1610005055,"timeUseconds":431396},{"captureId":"2099","correlation_id":"MjYwNmIwNDQyMTI5N2ZlZDkyNzkxNDY3YmM4ZDBmZmE.","create_date":"2021-01-07T07:37:38.445471Z","dbnode":"local","dstIp":"203.153.53.140","dstPort":50095,"id":75,"node":["2099","local"],"payloadType":5,"profile":"","proto":"rtcp","protocol":17,"protocolFamily":2,"raw":"{ \"sender_information\":{\"ntp_timestamp_sec\":3818993859,\"ntp_timestamp_usec\":1151051235,\"octets\":181288,\"rtp_timestamp\":2542680, \"packets\":1054},\"ssrc\":2571351459,\"type\":200,\"report_count\":1,\"report_blocks\":[{\"source_ssrc\":96552961,\"highest_seq_no\":14797,\"fraction_lost\":0,\"ia_jitter\":22,\"packets_lost\":0,\"lsr\":0,\"dlsr\":0}],\"sdes_report_count\":1,\"sdes_information\": [ {\"sdes_chunk_ssrc\":2571351459,\"type\":1,\"text\":\"6F34204489AE4BB09E80D6356EE7CBB3@unique.zB7EA455E93BC46D1.org\"},{\"sdes_chunk_ssrc\":2571351459,\"type\":8,\"text\":\"\u0010x-rtp-session-id0BAD9E87788B420A9E1F74928434C64C\"}] }","sid":"MjYwNmIwNDQyMTI5N2ZlZDkyNzkxNDY3YmM4ZDBmZmE.","srcIp":"203.153.53.157","srcPort":18193,"timeSeconds":1610005058,"timeUseconds":445471},{"captureId":"2099","correlation_id":"MjYwNmIwNDQyMTI5N2ZlZDkyNzkxNDY3YmM4ZDBmZmE.","create_date":"2021-01-07T07:37:41.455902Z","dbnode":"local","dstIp":"203.153.53.140","dstPort":50095,"id":76,"node":["local","2099"],"payloadType":5,"profile":"","proto":"rtcp","protocol":17,"protocolFamily":2,"raw":"{ \"sender_information\":{\"ntp_timestamp_sec\":3818993862,\"ntp_timestamp_usec\":1155346203,\"octets\":207088,\"rtp_timestamp\":2566680, \"packets\":1204},\"ssrc\":2571351459,\"type\":200,\"report_count\":1,\"report_blocks\":[{\"source_ssrc\":96552961,\"highest_seq_no\":14947,\"fraction_lost\":0,\"ia_jitter\":15,\"packets_lost\":0,\"lsr\":0,\"dlsr\":0}],\"sdes_report_count\":1,\"sdes_information\": [ {\"sdes_chunk_ssrc\":2571351459,\"type\":1,\"text\":\"6F34204489AE4BB09E80D6356EE7CBB3@unique.zB7EA455E93BC46D1.org\"},{\"sdes_chunk_ssrc\":2571351459,\"type\":8,\"text\":\"\u0010x-rtp-session-id0BAD9E87788B420A9E1F74928434C64C\"}] }","sid":"MjYwNmIwNDQyMTI5N2ZlZDkyNzkxNDY3YmM4ZDBmZmE.","srcIp":"203.153.53.157","srcPort":18193,"timeSeconds":1610005061,"timeUseconds":455902},{"captureId":"2099","correlation_id":"MjYwNmIwNDQyMTI5N2ZlZDkyNzkxNDY3YmM4ZDBmZmE.","create_date":"2021-01-07T07:37:44.470987Z","dbnode":"local","dstIp":"203.153.53.140","dstPort":50095,"id":77,"node":["local","2099"],"payloadType":5,"profile":"","proto":"rtcp","protocol":17,"protocolFamily":2,"raw":"{ \"sender_information\":{\"ntp_timestamp_sec\":3818993865,\"ntp_timestamp_usec\":1236950581,\"octets\":233060,\"rtp_timestamp\":2590840, \"packets\":1355},\"ssrc\":2571351459,\"type\":200,\"report_count\":1,\"report_blocks\":[{\"source_ssrc\":96552961,\"highest_seq_no\":15098,\"fraction_lost\":0,\"ia_jitter\":15,\"packets_lost\":0,\"lsr\":0,\"dlsr\":0}],\"sdes_report_count\":1,\"sdes_information\": [ {\"sdes_chunk_ssrc\":2571351459,\"type\":1,\"text\":\"6F34204489AE4BB09E80D6356EE7CBB3@unique.zB7EA455E93BC46D1.org\"},{\"sdes_chunk_ssrc\":2571351459,\"type\":8,\"text\":\"\u0010x-rtp-session-id0BAD9E87788B420A9E1F74928434C64C\"}] }","sid":"MjYwNmIwNDQyMTI5N2ZlZDkyNzkxNDY3YmM4ZDBmZmE.","srcIp":"203.153.53.157","srcPort":18193,"timeSeconds":1610005064,"timeUseconds":470987},{"captureId":"2099","correlation_id":"MjYwNmIwNDQyMTI5N2ZlZDkyNzkxNDY3YmM4ZDBmZmE.","create_date":"2021-01-07T07:37:47.481363Z","dbnode":"local","dstIp":"203.153.53.140","dstPort":50095,"id":78,"node":["2099","local"],"payloadType":5,"profile":"","proto":"rtcp","protocol":17,"protocolFamily":2,"raw":"{ \"sender_information\":{\"ntp_timestamp_sec\":3818993868,\"ntp_timestamp_usec\":1322849927,\"octets\":259032,\"rtp_timestamp\":2615000, \"packets\":1506},\"ssrc\":2571351459,\"type\":200,\"report_count\":1,\"report_blocks\":[{\"source_ssrc\":96552961,\"highest_seq_no\":15247,\"fraction_lost\":0,\"ia_jitter\":15,\"packets_lost\":0,\"lsr\":0,\"dlsr\":0}],\"sdes_report_count\":1,\"sdes_information\": [ {\"sdes_chunk_ssrc\":2571351459,\"type\":1,\"text\":\"6F34204489AE4BB09E80D6356EE7CBB3@unique.zB7EA455E93BC46D1.org\"},{\"sdes_chunk_ssrc\":2571351459,\"type\":8,\"text\":\"\u0010x-rtp-session-id0BAD9E87788B420A9E1F74928434C64C\"}] }","sid":"MjYwNmIwNDQyMTI5N2ZlZDkyNzkxNDY3YmM4ZDBmZmE.","srcIp":"203.153.53.157","srcPort":18193,"timeSeconds":1610005067,"timeUseconds":481363},{"captureId":"2099","correlation_id":"MjYwNmIwNDQyMTI5N2ZlZDkyNzkxNDY3YmM4ZDBmZmE.","create_date":"2021-01-07T07:37:50.495683Z","dbnode":"local","dstIp":"203.153.53.140","dstPort":50095,"id":79,"node":["local","2099"],"payloadType":5,"profile":"","proto":"rtcp","protocol":17,"protocolFamily":2,"raw":"{ \"sender_information\":{\"ntp_timestamp_sec\":3818993871,\"ntp_timestamp_usec\":1322849927,\"octets\":284832,\"rtp_timestamp\":2639000, \"packets\":1656},\"ssrc\":2571351459,\"type\":200,\"report_count\":1,\"report_blocks\":[{\"source_ssrc\":96552961,\"highest_seq_no\":15398,\"fraction_lost\":0,\"ia_jitter\":15,\"packets_lost\":0,\"lsr\":0,\"dlsr\":0}],\"sdes_report_count\":1,\"sdes_information\": [ {\"sdes_chunk_ssrc\":2571351459,\"type\":1,\"text\":\"6F34204489AE4BB09E80D6356EE7CBB3@unique.zB7EA455E93BC46D1.org\"},{\"sdes_chunk_ssrc\":2571351459,\"type\":8,\"text\":\"\u0010x-rtp-session-id0BAD9E87788B420A9E1F74928434C64C\"}] }","sid":"MjYwNmIwNDQyMTI5N2ZlZDkyNzkxNDY3YmM4ZDBmZmE.","srcIp":"203.153.53.157","srcPort":18193,"timeSeconds":1610005070,"timeUseconds":495683},{"captureId":"2099","correlation_id":"MjYwNmIwNDQyMTI5N2ZlZDkyNzkxNDY3YmM4ZDBmZmE.","create_date":"2021-01-07T07:37:52.791291Z","dbnode":"local","dstIp":"203.153.53.140","dstPort":50095,"id":80,"node":["local","2099"],"payloadType":5,"profile":"","proto":"rtcp","protocol":17,"protocolFamily":2,"raw":"{ \"sender_information\":{\"ntp_timestamp_sec\":3818993873,\"ntp_timestamp_usec\":2611340116,\"octets\":304612,\"rtp_timestamp\":2657400, \"packets\":1771},\"ssrc\":2571351459,\"type\":200,\"report_count\":0,\"report_blocks\":[],\"sdes_report_count\":1,\"sdes_information\": [ {\"sdes_chunk_ssrc\":2571351459,\"type\":1,\"text\":\"6F34204489AE4BB09E80D6356EE7CBB3@unique.zB7EA455E93BC46D1.org\"},{\"sdes_chunk_ssrc\":2571351459,\"type\":8,\"text\":\"\u0010x-rtp-session-id0BAD9E87788B420A9E1F74928434C64C\"}] }","sid":"MjYwNmIwNDQyMTI5N2ZlZDkyNzkxNDY3YmM4ZDBmZmE.","srcIp":"203.153.53.157","srcPort":18193,"timeSeconds":1610005072,"timeUseconds":791291}],"total":13},"rtp":{"data":[],"total":0}}`

![image](https://user-images.githubusercontent.com/66463347/103875163-1935cd80-50f8-11eb-8e0a-53ffe4da22c9.PNG)

Also added a image that shows the response.

**Comment by adubovikov** [comment]
I see, it was coded as "\u0010" , need to improve exeption and ignoreit

**Comment by sunilmmore** [comment]
@adubovikov glad that we got it . will wait for you next update .
