### ISSUE TITLE
No packetdata visible when i click on a packet

### ISSUE THREAD

**Issue by trideeindhoven** [sipcapture/homer-ui#39]
I am using the latest webhomer 5 git checkout using nginx and php-fpm.

I can see packets when i search in webhomer:
![screenshot1](https://cloud.githubusercontent.com/assets/9008122/11244260/f60466a4-8e0c-11e5-867c-a4f519cc1cd1.png)

but when i click on one of the packets, i see (everything empty):
![screenshot2](https://cloud.githubusercontent.com/assets/9008122/11244174/74b96e3c-8e0c-11e5-92e6-442879fd618c.png)

Strangely enough, when i click on the "callid", i can see the graphical visualization of the communication:

![screenshot3](https://cloud.githubusercontent.com/assets/9008122/11244214/aea0534a-8e0c-11e5-99c4-1dc8aba1913e.png)

Is this a bug or a configuration error/item?

**Comment by adubovikov** [comment]
Hi,

check your time on the capture server and on the capture node, they are 
not synced.

Wbr,
Alexandr

**Comment by trideeindhoven** [comment]
Hello Alexandr,

Thank you for the quick reply!
I have double-checked this and the time on the two nodes is correct:
Capture node: Wed Nov 18 16:10:31 CET 2015
Webhomer node: Wed Nov 18 16:10:31 CET 2015

In preferences i have:
define('HOMER_TIMEZONE', "Europe/Amsterdam");

In php.ini:
date.timezone = Europe/Amsterdam

Still i do see all timestamps in UTC and not in CET.

**Comment by lmangani** [comment]
Internal dates are and should be in UTC. TZ conversion is done on the UI with the timezone parameter

**Comment by adubovikov** [comment]
I am talking about real time sync, not a timezone. Please use ntpdate to 
sync it.

Wbr,
Alexandr

**Comment by trideeindhoven** [comment]
Solved! I guess changing timezone in php.ini and restarting nginx was the key. Thank you so much for pointing this out (it seemed like something to fix in a later stage!).
