### ISSUE TITLE
Failure to extract in Windows due to same file names in different case

### ISSUE THREAD

**Issue by Jaykah** [sipcapture/homer-ui#40]
Has encountered an issue with files located here: https://github.com/sipcapture/homer-ui/tree/master/lib/sweetalert

The files are named the same in a different case, which caused one to overwrite the other in Windows causing all kinds of funky stuff when transferred to the server.

I think it would make sense to rename one of them.

**Comment by adubovikov** [comment]
done.
https://github.com/sipcapture/homer-ui/commit/6b8fee7ccdde564101e88757bffc09743659eb7b
