### ISSUE TITLE
username not found

### ISSUE THREAD

**Issue by Gomam0n** [sipcapture/homer-ui#416]
I compile and install heplify-server, homer-app and homer-ui successfully and I run them. I can see the homer login interface in the 8080 port. But when I type in "admin" as username and "sipcapture" as password, a red error box "Not Found" appears. Does that mean I use the wrong username and password? How can I change them(in the source code)?
![202166-12311](https://user-images.githubusercontent.com/39645704/120912129-45fa0b00-c6bf-11eb-8625-7f155c471c2b.png)

**Comment by Gomam0n** [comment]
I think I use the homer-ui in a wrong way....

**Comment by lmangani** [comment]
Did you use the `homer-app` manually or via an installer? the application needs a backend, its not just client-side UI.

**Comment by Gomam0n** [comment]
I set up homer-app manually.  Actually I ran homer-ui by `ng serve --open --host 0.0.0.0 --port 8080 --source-map=false --vendorChunk=false --aot=true --disableHostCheck
` and opened the port 8080 so I got the problem above... 
I thought I should change the `http_settings` in `webapp_config.json` to the route of `dist` in `homer-ui`. Then I opened the port 9080 and I logged in successfully.

**Comment by adubovikov** [comment]
this is wrong approach. You should not use ng serve until you are developing it. Please check the procedure here:

https://github.com/sipcapture/homer-app

and here

https://github.com/sipcapture/homer-app/blob/master/scripts/build_frontend.sh


or just install package
