### ISSUE TITLE
Please, don't do stuff like this. 

### ISSUE THREAD

**Issue by systemcrash** [sipcapture/homer-ui#417]
Let the user decide what's too big or small. "Try to be useful". I would accept a different background colour, but obliterating the window content is...... bad.

Also, "its" (possessive form of it) and not "it's" (it is). 

https://github.com/sipcapture/homer-ui/blob/5c2695960915c3440a00786edb3db2661c528414/src/app/components/dashboard/dashboard.component.html#L41

**Comment by lmangani** [comment]
I very much agree with @systemcrash the current approach is a bit too violent and does not take into account screen size - also, just perhaps we should relegate those messages in an external dictionary file to allow easier control over grammar and syntax as well as translation.

**Comment by systemcrash** [comment]
It's a battle - see the message in context, or not.... strings 😢

**Comment by adubovikov** [comment]
@AlexeyOplachko any progress on it ?

**Comment by systemcrash** [comment]
This stuff still happening in homer 1.4......

![Screenshot 2021-09-03 at 14 59 21](https://user-images.githubusercontent.com/647633/132009433-1feade29-e813-4de6-aff2-b58bc889c919.png)



1. It's is a contraction, meaning a shorter or "contracted" form of "it is" or "it has." (Example: It's going to rain.)
1. Its is a possessive pronoun meaning, "belonging to it," or a "quality of it" (Example: The carrier lost its license) or (Example: Its color is red.)
1.  And there's absolutely, positively no such word as its'.

**Comment by AlexeyOplachko** [comment]
Hi @systemcrash can you please verify UI version for us? Because UI shown on screenshot seems outdated, some of the stuff that we'd expect to be present is not there.

**Comment by lmangani** [comment]
> And there's absolutely, positively no such word as its'.

@systemcrash the pointer is appreciated, none of us is or claims to be a native speaker, but there's really no need to lecture the full thread as if we were barbarians. You just noticed it first, and that's fantastic and plenty in order to correct the problem without insulting anyone's intelligence :)

**Comment by adubovikov** [comment]
i will keep it open for a while.... :-)

**Comment by systemcrash** [comment]
> @systemcrash the pointer is appreciated, none of us is or claims to be a native speaker, but there's really no need to lecture the full thread as if we were barbarians. You just noticed it first, and that's fantastic and plenty in order to correct the problem without insulting anyone's intelligence :)

I agree, I just copy/pasted from the top hit: https://www.faa.gov/about/initiatives/plain_language/articles/its/ 🤷  Sorry...

**Comment by systemcrash** [comment]
> Hi @systemcrash can you please verify UI version for us? Because UI shown on screenshot seems outdated, some of the stuff that we'd expect to be present is not there. Latest should be 7.10.1

You could be right - I might need to clear my browser cache after upgrading the docker image. I thought it weird that it crept back in again.

**Comment by adubovikov** [comment]
ah, so, it was just simple cache. Now it's time give a good feedback :-)
