### ISSUE TITLE
QoS chart has 1px wide bars, barely readable/usable

### ISSUE THREAD

**Issue by zerodeux** [sipcapture/homer-ui#419]
![homer-qos-1px-bars](https://user-images.githubusercontent.com/1296362/122045104-98cd7400-cddd-11eb-9a7f-65388d13d842.png)

On a regular HD display it's already hard to read and pick with the mouse. On HiDPI it's impossible...

Would it be possible to display larger bars ?

**Comment by RFbkak37y3kIY** [comment]
After homer will update to follow release package, it can be use mouse will for resize chart for QOS

![HOMER 7 9 13(dev) - Google Chrome 2021-07-02 18-20-05](https://user-images.githubusercontent.com/10195789/124296533-c1d26080-db62-11eb-9dea-8a87543f0703.gif)
