### ISSUE TITLE
When will be the next release cut? Last one was from July 2, 2020. 

### ISSUE THREAD

**Issue by pgopu** [sipcapture/homer-ui#424]
As other features are added, it would help for us to use a cut release than getting latest from any specific branch. Thank you!

**Comment by lmangani** [comment]
Hello @pgopu thanks for the question. 
Our build system has greatly changed - we will remove those old releases very soon.  Currently `homer-ui` doesn't have releases as its only built and bundled inside [homer-app](https://github.com/sipcapture/homer-app). So you can assume every `homer-app` release being a tandem `homer-ui` release, last being Jun 8 2021
