### ISSUE TITLE
Missing navbar logo

### ISSUE THREAD

**Issue by giangi** [sipcapture/homer-ui#44]
Hello,

being quite visible, I am sure you already noticed it, but the navbar logo points to a file deleted in https://github.com/sipcapture/homer-ui/commit/3f1f3c47ea73d5d0519551dd798c4078dc3efbb7. I would try to adjust https://github.com/sipcapture/homer-ui/blob/master/templates/header.html, but I fear to meddle with cosmetic choices (though I find img/homer_logo.png fits nicely).

**Comment by lmangani** [comment]
Thanks for catching this - Fixing next

**Comment by lmangani** [comment]
Fixed with 5e61ae80f5c08bae13087e52e322e871d8ac93c9
Thanks again for your report
