### ISSUE TITLE
Flow export as PNG

### ISSUE THREAD

**Issue by AlexeyOplachko** [sipcapture/homer-ui#479]
When exporting Flow as PNG "arrows" in packets are aligned incorrectly. 
1)  One column wide arrow are shorter than space between vertical lines i.e. 
![image](https://user-images.githubusercontent.com/45398541/132020033-4315e3ab-9521-49aa-bcf9-fc13118954cf.png)

2) Multi-column arrows are also shorter and in addition to that they stick out beyond the vertical line on the left 
![image](https://user-images.githubusercontent.com/45398541/132020499-46d38c90-a0a3-4264-a608-2bab344f8b12.png)

3) "Circle" ones are misaligned from their respective vertical line 
![image](https://user-images.githubusercontent.com/45398541/132020130-7c837fac-c934-450e-96c7-8d8acf571bdc.png)

**Comment by adubovikov** [comment]
@AlexeyOplachko should we close it ?
