### ISSUE TITLE
Autorefresh not working

### ISSUE THREAD

**Issue by ghmj2417** [sipcapture/homer-ui#490]
Built source from master on September 11.  Select an Autorefresh time, nothing happens except the refresh image blinks.

**Comment by adubovikov** [comment]
Thanks!

**Comment by adubovikov** [comment]
![HOMER-7-10-2](https://user-images.githubusercontent.com/4513061/132989513-76c080fa-812f-4305-92da-55a346c265c2.png)

Check here

**Comment by adubovikov** [comment]
@ghmj2417 you know that you have to do here :-) https://github.com/sipcapture/homer/stargazers

**Comment by ghmj2417** [comment]
@adubovikov Thank you for pointing out the new setting.  It is a new setting right? I doubt I would have ever found that.

**Comment by ghmj2417** [comment]
> @ghmj2417 you know that you have to do here :-) https://github.com/sipcapture/homer/stargazers

To be clear, for the Homer project you would like for me to open issues here?

**Comment by adubovikov** [comment]
if it's related to UI - better open in this repository. My point was to give us a star :-)  klick here - https://github.com/sipcapture/homer/stargazers

**Comment by ghmj2417** [comment]
@adubovikov Gotcha.  Star has been given.  Back to this new widget setting.  Is this stored on the client side browser or is this stored as a key:value in the database?

**Comment by adubovikov** [comment]
this is local storage settings. This means that will be stored into your
browser DB

**Comment by ghmj2417** [comment]
`this is local storage settings. This means that will be stored into your
browser DB`

I would like to make a vote for updating this to also look at a key:value pair in the json stored in the server Db.  We have many users with corporate PCs, laptops, etc with many widgets.  It will be very cumbersome to make those changes manually.  If the value was stored in the Db, I could write a script to change all the users.
