### ISSUE TITLE
SSL warning due to google fonts CSS

### ISSUE THREAD

**Issue by heytensai** [sipcapture/homer-ui#50]
I installed Homer to an SSL server and in browser received a warning about mixed content. The CSS files are linking to http://fonts.googleapis.com.

As suggested in https://github.com/sipcapture/homer-ui/pull/49 changing the URL to not require http would clear this up.

The two files I found are css/homer.min.css and apidoc/html/main.js.

**Comment by lmangani** [comment]
Please check if 23d5ceb7ba6bbca1fef501f39a5677b224159d29 resolves your issue

**Comment by heytensai** [comment]
Yes, this worked. Thanks for the quick fix.

**Comment by lmangani** [comment]
Thanks for your report!
