### ISSUE TITLE
RTCP view

### ISSUE THREAD

**Issue by microgiantya** [sipcapture/homer-ui#502]
Hello dear devs!

In call flow window can't totally disable rtcp info

Does this incorrect installation?

Images was created with version 4.2, but after update to 4.14 call flow looks the same((

![Screenshot 2021-10-05 at 19-00-02 homer 7 10 1](https://user-images.githubusercontent.com/81983258/136074293-bb164176-0ea7-489e-af38-a7bdae607139.png)
![Screenshot 2021-10-05 at 19-00-14 homer 7 10 1](https://user-images.githubusercontent.com/81983258/136074297-a1211ca2-3156-447d-a2b9-9c86724f8304.png)

PS: I don't know issue this is or not, so write here (do not curse me :))).

**Comment by adubovikov** [comment]
thank you! It has been fixed already in the devel branch. We will release it shortly.

**Comment by microgiantya** [comment]
Good news!
