### ISSUE TITLE
Search broken after 16:00

### ISSUE THREAD

**Issue by heimdull** [sipcapture/homer-ui#52]
My install is version 5.0.2 installed using manual install. 

Problem: When searching for all (Just clicking search) after 4:05 pm I get nothing in the output unless I set time range to something higher than 3-6 hours. Everything works fine before 4pm but for some reason things are broken after. When midnight comes around things start working again when time rotates to the am.

errors:
2016/01/25 16:48:53 [error] 20639#0: *1795 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: node in /var/vhosts/sipcapture/api/RestApi/Search.php on line 599" while reading response header from upstream, client: 10.4.1.13, server: homer01.xxx.com, request: "POST /api/v1/search/transaction HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "homer01.xxx.com", referrer: "http://homer01.xxx.com/"
2016/01/25 16:48:53 [error] 20639#0: *1797 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: node in /var/vhosts/sipcapture/api/RestApi/Report.php on line 74" while reading response header from upstream, client: 10.4.1.13, server: homer01.xxx.com, request: "POST /api/v1/report/rtcp HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "homer01.xxx.com", referrer: "http://homer01.xxx.com/"
2016/01/25 16:48:53 [error] 20639#0: *1798 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: node in /var/vhosts/sipcapture/api/RestApi/Report.php on line 184" while reading response header from upstream, client: 10.4.1.13, server: homer01.xxx.com, request: "POST /api/v1/report/log HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "homer01.xxx.com", referrer: "http://homer01.xxx.com/"
2016/01/25 16:48:53 [error] 20639#0: *1800 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: node in /var/vhosts/sipcapture/api/RestApi/Report.php on line 277" while reading response header from upstream, client: 10.4.1.13, server: homer01.xxx.com, request: "POST /api/v1/report/quality/short HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "homer01.xxx.com", referrer: "http://homer01.xxx.com/"

**Comment by lmangani** [comment]
could you share your timezone settings for both homer server and capture agents?

**Comment by heimdull** [comment]
preferences.php:
define('HOMER_TIMEZONE', "America/Los_Angeles");

root@homer01:/etc/kamailio# date
Mon Jan 25 17:58:20 PST 2016
root@homer01:/etc/kamailio# date +%Z
PST

**Comment by adubovikov** [comment]
Freddy also check the time on both server. Are they sync ?

Wbr,
Alexandr

**Comment by heimdull** [comment]
yes both servers are syncing from the same internal ntp server.
kamailio03:~$ date
Tue Jan 26 06:29:34 PST 2016
homer01:~$ date
Tue Jan 26 06:29:35 PST 2016

do you want to see something out of my database? looking at a captured invite thats from before 4pm and one after they look the same so I think this is a ui issue only, not capture issue.

My kamailio is using this config:

#!ifdef WITH_SIPTRACE
modparam("siptrace", "trace_on", 1)
modparam("siptrace", "trace_flag", 22)
modparam("siptrace", "trace_to_database", 0)
modparam("siptrace", "duplicate_uri", "sip:homer01.xxx.com:9060")
modparam("siptrace", "hep_mode_on", 1)
modparam("siptrace", "hep_version", 2)
#!endif

request_route {

#!ifdef WITH_SIPTRACE
    sip_trace();
    setflag(22);
#!endif

and capture server is using kamailio with the example config.

**Comment by lmangani** [comment]
@heimdull from your browser console try to capture a working and non working pair of request/response to/from the Homer API and post here for troubleshooting this further

**Comment by heimdull** [comment]
I just pulled these two packets from mysql. 3384224 works fine when I search for it in the ui, 3384319 does show in search window but has no data. 

  mysql> select id,date,micro_ts,method,callid from sip_capture_call_20160125 WHERE method='ACK' and date='2016-01-25 16:10:00' limit 1;
  +---------+---------------------+------------------+--------+----------------------------------------------+
  | id      | date                | micro_ts         | method | callid                                       |
  +---------+---------------------+------------------+--------+----------------------------------------------+
  | 3384224 | 2016-01-25 16:10:00 | 1453767000106818 | ACK    | 03fefa1e5039755c773e2a323f111d21@1.1.1.1     |
  +---------+---------------------+------------------+--------+----------------------------------------------+
  1 row in set (0.01 sec)

  mysql> select id,date,micro_ts,method,callid from sip_capture_call_20160125 WHERE method='ACK' and date='2016-01-25 16:10:01' limit 1;
  +---------+---------------------+------------------+--------+----------------------------------------------+
  | id      | date                | micro_ts         | method | callid                                       |
  +---------+---------------------+------------------+--------+----------------------------------------------+
  | 3384319 | 2016-01-25 16:10:01 | 1453767001032369 | ACK    | 71c76f6516a217192b653b567572e116@1.1.1.1     |
  +---------+---------------------+------------------+--------+----------------------------------------------+
  1 row in set (0.01 sec)

**Comment by heimdull** [comment]
Upgraded capture server (kamailio to latest 4.3 from github master)
and change kamailio.cfg to : 

#For old models. Not accurate insert time. System vs capture time.
#$var(a) = $var(table) + "_" + $timef(%Y%m%d);
#for Kamailio >4.3 please uncomment this parameters:
$var(a) = $var(table) + "_%Y%m%d";

everything is now working like expected.

**Comment by lmangani** [comment]
case added to Wiki/FAQ
