### ISSUE TITLE
LDAP Groupmembership does not work

### ISSUE THREAD

**Issue by mmonka** [sipcapture/homer-ui#53]
To compare uid 'check_filegroup_membership' needs the uid of the user, not the dn.
I check homer 3.5 and there $param['username'] is used; in homer5 $result[0]['dn'].

Any reason why you compare against dn?

diff --git a/api/Authentication/LDAP.php b/api/Authentication/LDAP.php
index f14760a..7ee4bd9 100644
--- a/api/Authentication/LDAP.php
+++ b/api/Authentication/LDAP.php
@@ -84,7 +84,7 @@ class LDAP extends Authentication {
 
 
                                      if (defined("LDAP_GROUPDN")) {
-                                        if (!$this->check_filegroup_membership($ds,$result[0]['dn'])) {
+                                        if (!$this->check_filegroup_membership($ds,$result[0]['uid'][0])) {
                                             return false;
                                         }
                                     }

**Comment by adubovikov** [comment]
in the homer 3.5 we have used also dn
https://github.com/sipcapture/homer/blob/homer3/webhomer/class/auth/ldap/auth.php

the fix:

https://github.com/sipcapture/homer/commit/f522ae30bbe864dd93b2d6ce477bc9ea11e32957

Line 72:  Compat: This works for Active Directory, but might horribly break other directory services.  Creating a constant in preferences called "ACTIVE_DIRECTORY" and checking that and determining whether to pass $username or $result[0]['dn'] would be better.

we can change it to a php constant variable

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-api/commit/47400c86c7b7cfeba8ccbd56c347a0648dfe9a07

and

https://github.com/sipcapture/homer-api/commit/29c40947bd2c49e9f31e08316083905803a3fe1d

please test

**Comment by mmonka** [comment]
should be: 
$result[0][LDAP_GROUP_USER][0]
                                                      ^^
if (!$this->check_filegroup_membership($ds,$result[0][LDAP_GROUP_USER][0])) {

then it works!

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-api/commit/9f42f03e91b8fe565b7fbc9cd5fd2a2b75dd72ad

https://github.com/sipcapture/homer-api/commit/c22c2ca6f0cfe2954a99817e18e926b99ba7161b

**Comment by mmonka** [comment]
That looks good for us now. But it looks like you have to put the new grp values for admins also to $_SESSION:

diff --git a/api/Authentication/LDAP.php b/api/Authentication/LDAP.php
index dff73e5..b43fc90 100644
--- a/api/Authentication/LDAP.php
+++ b/api/Authentication/LDAP.php
@@ -124,6 +124,7 @@ class LDAP extends Authentication {
                             if ($value == $param['username']) {
                                 $_SESSION['userlevel'] = 1; # LDAP_ADMINLEVEL;
                                 $user['grp'] = "users,admins";
+                               $_SESSION['grp'] = "users,admins";
                             }
                         }
                         return $user;

**Comment by rbott** [comment]
The pull request for this fix has already been accepted. I guess we can close this issue then :-)
