### ISSUE TITLE
invisible search parameters will still be considered for search

### ISSUE THREAD

**Issue by rbott** [sipcapture/homer-ui#57]
When you remove a field (e.g. "Auth User") from the search panel but have used it before, there might still be a value saved in the settings table. From what we have observed, these parameters are still included in searches - unknown to the user, because the field is not visible.

Is this intentional or considered a bug?

**Comment by nicodemus** [comment]
I have experienced the same issue, with 'source_ip' being included in the WHERE clause, with no value being specified in the GUI. Returning to the search panel and clicking 'Clear' seems to fix it.

**Comment by lmangani** [comment]
could either of you confirm if this is still an issue with the latest UI/API git version? Thanks

**Comment by mmonka** [comment]
We tested this behavior with a version from july, 26th (d61773c) today. 
Bug still exists.

**Comment by lmangani** [comment]
Thanks for the update, will review. Are you loading the session with any URL parameters?

**Comment by adubovikov** [comment]
@mmonka can you please provide the JSON request ?

**Comment by boettner** [comment]
I removed the field "protocol" from the search form, but its former value is still included in the search request:
```
{"id":"search","param":{"to_user":"4921163555533","from_user":"4921163555533","orand":true,"proto":"tcp","limit":"1000"}}
```
This gets posted to: /api/v1/profile/store/search

We also saw that search values are stored in the settings database:
```
mysql> select * from setting where uid = 3054 and param_name = "search";
+----+------+------------+------------------------------------------------------------------------------------------------+---------------------+---------------------+------------+--------+
| id | uid  | param_name | param_value                                                                                    | valid_param_from    | valid_param_to      | param_prio | active |
+----+------+------------+------------------------------------------------------------------------------------------------+---------------------+---------------------+------------+--------+
|  7 | 3054 | search     | {"to_user":"4921163555533","from_user":"4921163555533","orand":true,"proto":"tcp","limit":"1000"} | 2012-01-01 00:00:00 | 2032-12-01 00:00:00 |         10 |      1 |
+----+------+------------+------------------------------------------------------------------------------------------------+---------------------+---------------------+------------+--------+
```

We would expect saved values are only considered when the form field is actually visible in the search form :-)

Hope that helps!

**Comment by adubovikov** [comment]
@boettner in the UI you have one global search object and once you created in the "FULL Search page" it will be available also for all "Quick search" widgets... If you want to clean up it, just press "Clear" and it should be done

**Comment by boettner** [comment]
Technically clear to me, but (our) users aren't expecting this behaviour.

Case:
Someone changes the "global search form" dashboard and removes a field. All other users (with pre-filled values) won't find any packets. Sure, they could press "Clear" but that's IMHO not obvious.

But I see the point. Maybe this is more an enhancement. Maybe we'll change this someday and make a pull request.

**Comment by adubovikov** [comment]
the best way IMHO, clean up the object and populate with current variables.
I will look on it later.
