### ISSUE TITLE
Angular bug - ng build error: Invalid version: "15.2-15.3"

### ISSUE THREAD

**Issue by ghmj2417** [sipcapture/homer-ui#572]
When building homer-ui, I am getting `"Error: Transform failed with 1 error:", "error: Invalid version: \"15.2-15.3\""` which is associated with this issue, https://github.com/angular/angular-cli/issues/22606.  The workaround is to update `.browserslistrc` by appending to the end
```
not ios_saf 15.2-15.3
not safari 15.2-15.3
```
I could do a PR but it might be quicker if you guys did it.

**Comment by ram3shyadav** [comment]
angular/angular-cli#22611

**Comment by ghmj2417** [comment]
Fixed via https://github.com/angular/angular-cli/pull/22611 which is posted by @ram3shyadav.
