### ISSUE TITLE
Erratic input in Smart Search field, Safari MacOS

### ISSUE THREAD

**Issue by billsimon** [sipcapture/homer-ui#588]
When trying to use the Smart Search field with Safari for MacOS, the cursor keeps jumping to the beginning of the search line as I type, making it impossible to correctly enter text.

This only affects Safari. It is not a problem with Firefox or Chrome/Chromium.

**Comment by billsimon** [comment]
Here is a video showing the problem I face with Safari. I am attempting to type "protocol" in order to specify a search object.

https://user-images.githubusercontent.com/5303782/168911992-af641658-b330-47e8-9b1f-a15491b8db30.mov

**Comment by adubovikov** [comment]
Of course we will check it, but we recommend use Chrome/Firefox for the UI

**Comment by RFbkak37y3kIY** [comment]
fixed https://github.com/sipcapture/homer-ui/pull/617
