### ISSUE TITLE
When copying a SIP message from results, line breaks get lost

### ISSUE THREAD

**Issue by SipSeb** [sipcapture/homer-ui#59]
I just tried copying a SIP message from the message view overlay, but when pasting it somewhere else, all the line breaks are lost.

I searched through the code of ui and api, but I have no clue, where I could play around with line breaks.

Could you fix that, please?

**Comment by lmangani** [comment]
@SipSeb I cannot replicate your issue, newlines are preserved when copy-pasting between the SIP Message details popup in Chrome and any other system editor. What browser/system are you using?

**Comment by SipSeb** [comment]
We tried it with a current Firefox 42.0 on Mac and Linux. But I just noticed, it must be a Firefox issue. When trying the same thing in Safari, it works.

**Comment by SipSeb** [comment]
Is there any possibility to get this fixed? We have quite a few users with Firefox as their default browser, and they are a bit annoyed by this bug. It's still happening in Firefox 47.

**Comment by lmangani** [comment]
@SipSeb we would be glad to, but this seems confirmed being a Firefox issue - if you know a workaround or pointer at similar discussions/solutions we'd be glad to take a look

**Comment by SipSeb** [comment]
I haven't found the line in the Homer-UI code, where this SIP package detail overlay is built. My guess would be, that there are only \n at the end of each line where \r\n could help already. 
Could you point me to the code part, where this is generated? Maybe I can look into this myself then.
