### ISSUE TITLE
Show hostname in callflow

### ISSUE THREAD

**Issue by ishmaelen** [sipcapture/homer-ui#60]
Hello,

Is it possible to use hostnames in call-flow instead of IPs? Pref. this should be configurable by the user.

Kind regards,

Andy

**Comment by lmangani** [comment]
Hi @ishmaelen 

This is possible since the inception of Homer - Please consult our Wiki to learn how to manage Aliases, also use to correlate traffic visually: https://github.com/sipcapture/homer/wiki/Using-Homer-5#aliases

**Comment by ishmaelen** [comment]
Ok! Thanks for the information. I was stupidly working under the false assumption Homer would use DNS/hosts to show hostnames from IPs and that you could add custom names in aliases etc.

**Comment by lmangani** [comment]
Glad if useful! Homer uses its internal aliasing to provide maximum flexibility in terms of pairing within the monitoring scope unrelated to the production names of elements (unless desired)

**Comment by ishmaelen** [comment]
This makes a lot of sense, especially considering the possible future feature to correlate seemingly unrelated streams of data (e.g. split SIP and RTP servers, REST calls and logs through HEPipe etc.).
