### ISSUE TITLE
dependecy tree error when running npm install

### ISSUE THREAD

**Issue by fabiantorress** [sipcapture/homer-ui#626]
Hi, I am having some errors when I run `npm install`:
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: homer-ui@7.8.1
npm ERR! Found: @angular/common@12.2.17
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^12.1.4" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^8.2.14" from ag-charts-angular@3.3.0
npm ERR! node_modules/ag-charts-angular
npm ERR!   ag-charts-angular@"^3.3.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
My server is Centos8, my node version is 20.5.0 and npm version 9.8.0.
What could be the reason?

**Comment by lmangani** [comment]
@fabiantorress the comand would be `npm run build` in this case but - unless you're planning to modify the code - you're not required to compile or install anything. The UI is embedded in the homer-app serving it.

**Comment by fabiantorress** [comment]
Yes, I am planning to modify the code.

**Comment by lmangani** [comment]
Great! Please refer to the github actions and docker files for a fully working example of a build pipeline.

**Comment by lmangani** [comment]
Feel free to ask any questions in the thread if you need help, or jump on the matrix channel

**Comment by fabiantorress** [comment]
Thanks @lmangani
