### ISSUE TITLE
Inconsistency in Displaying Call Legs When Accessing Flow via Shared Link in homer-ui

### ISSUE THREAD

**Issue by seabra** [sipcapture/homer-ui#628]
Hi there! 😊

**Issue Summary:**

I have encountered a small issue in homer-ui that I'd love some help with. When I go to search for a call and click on the flow, everything seems smooth. However, when I share the link for that call and check out the flow, it's not showing all the legs as expected. Let me walk you through the details.

**Steps to Reproduce:**

1. Perform a regular search in homer-ui.
2. Click on the flow of a call and you will see the entire flow(all legs).
3. Use the share link for the same call.
4. Click on the flow from the shared link, and despite having all packages, it only shows the first leg when clicking on the flow.

**Expected Behavior:**

When opening the flow using the shared link we should be able to see the exact same flow as we can see using the normal search UI

**Additional Info:**

- Normal Search Flow Request Payload:

```
POST to https://homer/api/v3/call/transaction with the following payload:
{
  "param": {
    "transaction": {
      "call": true,
      "registration": false,
      "rest": false
    },
    "limit": 200,
    "orlogic": false,
    "search": {
      "1_call": {
        "id": 14873683,
        "callid": [
          "v2qahpq1g8h3mxxxxxxx"
        ]
      }
    },
    "location": {},
    "timezone": {
      "value": -180,
      "name": "Local"
    }
  },
  "timestamp": {
    "from": 1709117802400,
    "to": 1709118402400
  }
}
```

- Shared Link Flow Request Payload:

```
POST to https://homer/api/v3/call/transaction with the following payload:
{
  "param": {
    "search": {
      "1_call": {
        "id": 14873683,
        "callid": [
          "v2qahpq1g8h3mxxxxxxx"
        ]
      }
    },
    "location": {
      "node": [
        "eu_west_1"
      ]
    },
    "transaction": {
      "call": true,
      "registration": false,
      "rest": false
    },
    "timezone": {
      "value": -180,
      "name": "Local"
    },
    "limit": 200
  },
  "timestamp": {
    "from": 1709117811531,
    "to": 1709118411531
  }
}
```
could you pls help understand what is wrong here!

**Comment by bilalrao12** [comment]
@seabra What version of homer app you are using.
also what is generated url when you click on share link
