### ISSUE TITLE
Protocol Filters

### ISSUE THREAD

**Issue by jagnetta** [sipcapture/homer-ui#630]
Good morning,

I hope this finds you all well.  I'm wondering about:  https://github.com/sipcapture/homer-ui/issues/289 and https://github.com/sipcapture/homer-ui/issues/369 where it looks like there maybe an attempt to add settings to control which types of messages appear in the ladder diagrams by default?  I'm hoping we can have a uniform set of options that can then be changed later on.  For example, we are sending xlog to homer from opensips, but we'd like the logs to not be shown in the ladder diagram by default.  Instead, default show SIP and RTCP, then allow the display of logging if desired through the filter.  

Related:  What's the difference between "LOG" and "HEP-LOG" that we're getting for each log message opensips sends?

Thanks,
Jim Agnetta

**Comment by lmangani** [comment]
In general HOMER will grab and display anything that correlation logic returns. For each session returned by the primary correlation loop (CallID, Correlation_ID, X-Headers, etc) it'll lookup corresponding RTCP (5) and LOG (100) HEP types and display them in the flow. The type filtering is local and only affect the individual browser session/client.

**Comment by jagnetta** [comment]
Understood.  Thanks Lorenzo!
