### ISSUE TITLE
Searching for Content within a Header

### ISSUE THREAD

**Issue by jagnetta** [sipcapture/homer-ui#631]
Good evening,

Included in our INVITEs is a header like this:

`X-CC-TRACE:  c=LnAQ2VOot4lBBBXKT46rHGY8bJOFdvT9;a=Agent1@JimAgnetta2;i=int-18f53d39bca-1vawdKEqAvzsUXVXohhKBuh9J-phone-00-JimAgnetta2
`

I am currently and successfully searching for this header, extracting the text following the "i=," and correlating A and B call legs using the extraction.  It's great.  The correlation ID appears as `int-18f53d39bca-1vawdKEqAvzsUXVXohhKBuh9J-phone-00-JimAgnetta2`

However, I've been given another request.  I'm being asked that we expose the X-CC-TRACE header as a searchable header in the CALL SIP SEARCH widget, which I've added; however, I'm unable to get any searching to work with this header.  Ideally we'd like to be able to search for the "c" or the "a" or the "i" values presented in that header.  So I figured it would be possible to do something like this in the search field:

%LnAQ2VOot4lBBBXKT46rHGY8bJOFdvT9%
or
%Agent1@JimAgnetta2%
or
%int-18f53d39bca-1vawdKEqAvzsUXVXohhKBuh9J-phone-00-JimAgnetta2%

I was expecting to yield the INVITE containing the X-CC-TRACE header above using any of those three search strings above, but nothing works, not even if I search for the entire field.

So, I'm not sure why I'm not able to search on partial strings within that header.  Any help?  I've attached mapping rule configurations.

[Fields mapping SIP call 2024-05-07 12_28_26.json](https://github.com/sipcapture/homer-ui/files/15238385/Fields.mapping.SIP.call.2024-05-07.12_28_26.json)
[Correlation mapping SIP call 2024-05-07 12_28_22.json](https://github.com/sipcapture/homer-ui/files/15238386/Correlation.mapping.SIP.call.2024-05-07.12_28_22.json)

**Comment by jagnetta** [comment]
I would also like to add.  I've exposed thee X-CC-TRACE column in the search results row, and the field is not populating there when the header is present in the message.  The column is just blank despite the presence of the header in that message.  So the field must not be making it in to the DB properly or something?

**Comment by lmangani** [comment]
@jagnetta correlation logic should be indeed completely separate and independent, but once a field exists its usually easy to map it ad-hoc with some type of logic in common with search. TLDR; if the extraction exists it can be used for dynamic correlation.
