### ISSUE TITLE
FEATURE REQUEST:  Setting Default Display Filter Behavior for a User

### ISSUE THREAD

**Issue by jagnetta** [sipcapture/homer-ui#632]
Good day,

Is there a parameter somewhere to select which of the display filters can be selected?  We'd like to enable SIP and RTCP but disable HEP_LOG and LOG by default, w/o needing to change it with each viewing of the call details, is it possible?

Thanks,
Jim

**Comment by jagnetta** [comment]
Hi @lmangani --  That's a great idea!

**Comment by jagnetta** [comment]
Feature Request:  Please add a feature to enable which of the display filters should be enabled or disabled for a user.

**Comment by jagnetta** [comment]
@lmangani somewhat related:

https://github.com/sipcapture/homer-ui/issues/177

**Comment by RFbkak37y3kIY** [comment]
[The task has expiredhttps://github.com/sipcapture/homer-ui/pull/641](https://github.com/sipcapture/homer-ui/pull/641)

needs add on Preference/Advenced -> 

category: transaction
param: filter

data:
```json
{
	"SIP": true,
	"RTP": true,
	"RTCP": true,
	"LOG": false,
	"HEP-LOG": false 
}
```

![image](https://github.com/user-attachments/assets/9636eac4-6ecb-4568-8d35-8c563633093a)
