### ISSUE TITLE
Style issues following migration to new angular version

### ISSUE THREAD

**Issue by AlexeyOplachko** [sipcapture/homer-ui#636]
Non-exhaustive list of examples:
![image](https://github.com/sipcapture/homer-ui/assets/45398541/8803b59f-afe0-4a66-a580-4c135850d361)
![image](https://github.com/sipcapture/homer-ui/assets/45398541/eb65c929-a953-479b-b085-48955eaf9422)
![image](https://github.com/sipcapture/homer-ui/assets/45398541/7ad6499f-b190-4c0a-acee-c8370ac29bfe)
![image](https://github.com/sipcapture/homer-ui/assets/45398541/35043173-8f7b-44b9-a1c0-836dd2336057)
![image](https://github.com/sipcapture/homer-ui/assets/45398541/fc86d020-2c8c-4112-8b2d-2a7ba18e3270)
![image](https://github.com/sipcapture/homer-ui/assets/45398541/c78ebc76-0a8d-46aa-8272-43ce4ad50a86)
![image](https://github.com/sipcapture/homer-ui/assets/45398541/94e7ccea-402c-4f89-b4fa-f64fe9710e26)
![image](https://github.com/sipcapture/homer-ui/assets/45398541/fb8459b5-6589-404b-bf59-fd2dcce9c722)
![image](https://github.com/sipcapture/homer-ui/assets/45398541/8aaae81e-6738-4516-bcd6-42ead16c6867)

**Comment by adubovikov** [comment]
merged
