### ISSUE TITLE
Creating New Users in Homer

### ISSUE THREAD

**Issue by jagnetta** [sipcapture/homer-ui#643]
Good morning,

When I create a new user in homer, only login credentials are created.  On login, there is no functional dashboard presented.  Is this expected?

Looking further, I find the User Settings which contain the dashboard settings for the default admin and support users, but none created for the new user.  Is the intention that the homer admin has to create dashboards for each user?

Are there any known ways to automate this process (i.e., create multiple users with dashboards) to some degree?

Ideally, I'd like all the users to start with the home, registration, and smart search dashboards in use by the admin user.

**Comment by lmangani** [comment]
Hi Jim, 
Please provide your procedure step-by-step so we can confirm its correct and/or reproduce your exact scenario.

**Comment by jagnetta** [comment]
I was logging in as the admin user.  Went to the "users" setting and clicked, add user.  Completed the dialog, and then I clicked save.  Logged out as the admin, then logged in with the new credentials.

That being said, I've worked around the whole thing by creating entries manually in the users and user_settings tables in the homer_config DB area....
