### ISSUE TITLE
Please clarify the licence of this repository

### ISSUE THREAD

**Issue by henningw** [sipcapture/homer-ui#644]
Thank you for providing this software. I am interested in the exact license of this repository. I tried to spot a LICENSE file or other licensing information in the source code, but I was unable to find it.

Can you please clarify the license of this software repository, e.g. by adding a LICENSE file in the top level directory? I have noticed that it includes the roboto font, licensed under Apache license, it should be probably listed as well in the README or so.

Thanks in advance.

**Comment by adubovikov** [comment]
Sure :-) 

Here you are:

https://github.com/sipcapture/homer-ui/blob/master/LICENSE

**Comment by lmangani** [comment]
> Thank you for providing this software. I am interested in the exact license of this repository.

May we know the reason for this interest? Are you planning on contributing?

**Comment by henningw** [comment]
> > Thank you for providing this software. I am interested in the exact license of this repository.
> 
> May we know the reason for this interest? Are you planning on contributing?

I did a license review of the main homer components, as there widely used, and just noticed that its missing here.
