### ISSUE TITLE
Share link

### ISSUE THREAD

**Issue by pinchasMT** [sipcapture/homer-ui#68]
when looking at sip flow, and then click on "export" , share link the link appears as:
http://your.public.host/share/#76623b52-92ef-4ab3-a98e-224becdf8168

please change **http://your.public.host** to correct link

**Comment by lmangani** [comment]
@pinchasMT this is defined in the preferences of Homer
If you pull the latest version and leave this field empty it will be auto determined by the client

**Comment by pinchasMT** [comment]
define('PUBLIC_SHARE_HOST','');

i get:
#26e9db7f-4121-4355-9c96-981297287097

**Comment by lmangani** [comment]
thats the intended behaviour. Update your API/UI code to the latest git version and the frontend will detect and append its own address.

**Comment by pinchasMT** [comment]
i think i"m on latest git version, how can i check?
