### ISSUE TITLE
5.0.5 rtcp-xr

### ISSUE THREAD

**Issue by pinchasMT** [sipcapture/homer-ui#69]
just updated to 5.0.4
the qos tab shows more info
but now there is no stats graph
i get rtcp-xr from sip:publish and they appear in db report_capture but no graph in qos

**Comment by adubovikov** [comment]
check if you have any "chart's data" in the API result.

**Comment by pinchasMT** [comment]
"chart": {
                    "RTCPXR  -> ": {
                        "mos": [
                            [
                                1459973506258,
                                0
                            ]
                        ],
                        "jitter": [
                            [
                                1459973506258,
                                0
                            ]
                        ],
                        "packets_lost": [
                            [
                                1459973506258,
                                0
                            ]
                        ]
                    },
                    "RTCPXR Array -> Array": {
                        "mos": [
                            [
                                1459973526260,
                                0
                            ],
                            [

On Wed, Apr 6, 2016 at 4:23 PM, Alexandr Dubovikov <notifications@github.com

**Comment by adubovikov** [comment]
so, please check the API procedure and if you have real data in your table

**Comment by lmangani** [comment]
Latest version is 5.0.5 please make sure this is your current version and update both API and UI

**Comment by pinchasMT** [comment]
ui is ver 5.0.5
how do i check API?
maybe it would be useful to add /api/v1/version
maybe it would be useful to put somewhere in ui version of ui and version of api

**Comment by lmangani** [comment]
Homer-UI and Homer-API are separate repositories but work in tandem. Best practice is to always update both at the same time: https://github.com/sipcapture/homer/wiki/Manual-Update

**Comment by pinchasMT** [comment]
did that at update today
but no stats graph in qos

**Comment by pinchasMT** [comment]
bump

**Comment by lmangani** [comment]
Are you positive you actually have RTCP data in your db?

**Comment by pinchasMT** [comment]
select count(*) from report_capture;
    +----------+
    | count(*) |
    +----------+
    |       66 |
    +----------+
    1 row in set (0.01 sec)

just to recap:
rtcp-xr was enabled on one phone for testing, phone does send sip "publish" , and i can see them in DB
but not in homer 5.0.5 in qos 
![image](https://cloud.githubusercontent.com/assets/17321963/14365782/78311cb4-fcdd-11e5-8654-85afb48286bb.png)

**Comment by lmangani** [comment]
The count doesn't really help understand much and Its hard to guess without seeing what the packets contained. Did they carry the SIP correct correlation ID for instance? Please share more details in order to get constructive responses.

**Comment by pinchasMT** [comment]
```
mysql> select * FROM report_capture ORDER BY id DESC LIMIT 1 \G
*************************** 1. row ***************************
              id: 71
            date: 2016-04-07 20:23:58
        micro_ts: 1460060638055077
  correlation_id: 0_214361200@192.168.1.7
       source_ip: XXX.XXX.XXX.XXX
     source_port: 1430
  destination_ip: XXX.XXX.XXX.XXX
destination_port: 5060
           proto: 1
          family: 2
            type: 1
            node: homer01:2001
             msg: PUBLISH sip:pnchtest.pinc...:5060 SIP/2.0
Via: SIP/2.0/UDP 192.168.1.7:5060;branch=z9hG4bK799939787
From: "201" <sip:201@pnchtest.pinc...:5060>;tag=1965948907
To: <sip:pnchtest.pinc...:5060>
Call-ID: 0_90119815@192.168.1.7
CSeq: 1 PUBLISH
Content-Type: application/vq-rtcpxr
Max-Forwards: 70
User-Agent: Yealink SIP-T29G 46.80.0.70
Event: vq-rtcpxr
Content-Length:   683

VQSessionReport: CallTerm
LocalMetrics:
Timestamps:START=2016-4-7 16:23:48 STOP=2016-4-7 16:23:57
SessionDesc:PT=0 SR=0 FD=0 FO=0 FPP=0 PPS=50 PLC=0 SSUP=off
CallID:0_214361200@192.168.1.7
ToID:<sip:pnchtest....>
FromID:"201"<sip:201@pnchtest.pinc...>
LocalAddr:IP=192.168.1.7 PORT=11960 SSRC=0x5ba50bd0
RemoteAddr:IP=xxx.xxx.xxx.xxx PORT=25794 SSRC=0x400f9c33
JitterBuffer:JBA=0 JBR=0 JBN=0 JBM=0 JBX=0
PacketLoss:NLR=0.0 JDR=0.0
BurstGapLoss:BLD=0.0 BD=0 GLD=0.0 GD=0 GMIN=0
Delay:RTD=0 ESD=0 SOWD=0 IAJ=0 MAJ=0
Signal:SL=0 NL=0 RERL=0
QualityEst:RCQ=0 EXTRI=0 MOSLQ=0.0 MOSCQ=0.0
DialogID:0_214361200@192.168.1.7;to-tag=5FD6U1Uvca3rQ;from-tag=2411520283
1 row in set (0.00 sec)
```

**Comment by pinchasMT** [comment]
i downloaded 5.0.1 ui and put it in subfolder "old" on my web server
created link api to ../api
and old ui does shows rtcp-xr call stats
![image](https://cloud.githubusercontent.com/assets/17321963/14392681/9b57a5ce-fd90-11e5-8ff0-3f32e7d1fc48.png)
but the new ui 5.0.5 doesnt

**Comment by adubovikov** [comment]
If you can provide us a sql dump of sip messages and rtcp reports we can 
check it local.

an email to support@ will be ok
