### ISSUE TITLE
PDD and ACD graphs

### ISSUE THREAD

**Issue by nshopik** [sipcapture/homer-ui#7]
So I'm trying to add new graphs PDD (using 95 percentile) and ACD, but I having trouble understanding query language, is this even possible? Or this should be stored in mysql before I can query?

**Comment by adubovikov** [comment]
if you use internal homer's statistic, it should be stored before. If you want to use Elasticsearch or InfluxDB it can be calculated in JS. Anyway, you can create a custom widget and do all calculation there.

**Comment by nshopik** [comment]
JS probably way to got instead storing it in mysql (just wasting space).

As eventually I would like to cover all performance metrics which is defined in RFC 6076

**Comment by adubovikov** [comment]
for RFC6076 better use kamailio.cfg and hashtable or check our old statistic script:

https://github.com/sipcapture/homer/blob/master/scripts/old/statistic.pl

but for some SESSION related metrics, you have to follow dialog match.

**Comment by nshopik** [comment]
I rather stay away from kamailio.cfg for now, its syntax doesn't make it easy.
