### ISSUE TITLE
Quick time ranges

### ISSUE THREAD

**Issue by onnet** [sipcapture/homer-ui#70]
Hi guys,

every time I use qick time ranges it feels like the one is missing - "Today"

Is there any reason it is absent or it wasn't created accidentally?

Regards,
Kirill

**Comment by lmangani** [comment]
Hi Kirill,

By Today you mean time from ```00:00:00``` to ```23:59:59``` or ```now```?

**Comment by onnet** [comment]
Hi Lorenzo,

I meant first option (00:00:00 to 23:59:59) to not to refresh time range every time I want to find a call I just placed. 

Regards,

**Comment by lmangani** [comment]
If this is for searching new calls, you should set the timer to "Next" position and auto-refresh at the same rate - have you tried that approach?

**Comment by onnet** [comment]
No, I didn't. 
But my experience says that I just want to login and be able to query calls fresh and old ones not thinking about time ranges within a day. I understand that time ranges could save you in case of having tons of calls per day. But in case of small/acceptable amount of calls it is a bit annoying.

**Comment by adubovikov** [comment]
Hello Kirill,

please check this commit:

https://github.com/sipcapture/homer-ui/commit/fa5a2f352d72a9518e2ade4f86caf5bd0f40ad8c

Wbr,
Alexandr

**Comment by onnet** [comment]
Hi Alexandr,

Works perfect.
Many thanks!

Regards,
