### ISSUE TITLE
Link button in export screen is broken 

### ISSUE THREAD

**Issue by wvamdyke** [sipcapture/homer-ui#74]
This is the link as provided
 
http://192.168.77.53/share//var/www/html/share/#49dd24f6-9982-4942-9c33-da73f92eaeb8

If I remove "share//var/www/html/" the link works 

http://192.168.77.53/share/#49dd24f6-9982-4942-9c33-da73f92eaeb8

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-api/blob/master/api/preferences_example.php#L75
