### ISSUE TITLE
timerange for automatic refresh not being update

### ISSUE THREAD

**Issue by RadicalDev** [sipcapture/homer-ui#76]
Hello,

The timerange.from and timerange.to values are not being updated in htdocs/js/controller.js: 394 so the result set returned is always the same where I think the intended behavior is to refresh the page every [interval] seconds to display new results.

I did the following simple thing which mostly does what I want it to do:

```
$scope.timerange.to = new Date();
$scope.timerange.from = new Date(new Date().setMinutes(new Date().getMinutes() - 10));
$scope.timerange.to.setSeconds($scope.timerange.to.getSeconds() + seconds);
```

**Comment by adubovikov** [comment]
@RadicalDev can you please do PR for this ? Thank you!

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/releases/tag/1.1.8
