### ISSUE TITLE
call duration in popup is not filled

### ISSUE THREAD

**Issue by denzs** [sipcapture/homer-ui#79]
The popup which is opend by clicking a callid from the search table always contains
"Session Duration: 00:00:00".

However the correct duration is part of the result like:

```
{
    "status": 200,
    "sid": "7i46op9b4r600cvoka767nmr45",
    "auth": "true",
    "message": "ok",
    "data": {
        "info": {
            "callid": [

            ],
            "totdur": "00:00:23",
            "statuscall": 1
        },
```

**Comment by lmangani** [comment]
Sorry about the late response here. This is a conditional case, so could you extend this ticket with more details, ie your query and the returned results? The response alone (expecially when not associated with the rest) is insufficient to determine the best solution.

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/releases/tag/1.1.8
