### ISSUE TITLE
remove any unused JavaScript

### ISSUE THREAD

**Issue by dpocock** [sipcapture/homer-ui#81]
Can you please look through the `lib` directory and remove any JavaScript that is not used by the project any more?  Each of these creates extra effort for packaging, so if any of them can be removed because they were used in the past but not used any more then it helps a lot.

https://github.com/sipcapture/homer-ui/tree/master/lib

**Comment by dpocock** [comment]
good news, homer-api was accepted in Debian today.  Getting homer-ui into Debian as well depends on sorting out these JavaScript issues.

**Comment by lmangani** [comment]
Thanks @dpocock without you this would never happen! We're working to clean up ```homer-ui``` asap

**Comment by StefanYohansson** [comment]
hey guys @lmangani @dpocock @adubovikov
Can I help?

I start looking. Here is my list of what's useless now:

- [x] filesaver
- [x] mermaid.min.js
- [x] mermaid.slim.min.js

mermaid verified with:
```
grep -R -i "mermaid" * | grep -v "lib/mermaid"
js/app.js://console.log(mermaid);
templates/dialogs/transaction.html:				<!-- mermaid placeholder -->
```

filesaver verified with:
```
grep -R -i "filesaver" *
dist/index.html:<script type="application/javascript" src="lib/filesaver/FileSaver.min.js"></script>  
index.html:<script type="application/javascript" src="lib/filesaver/FileSaver.min.js"></script>  
lib/filesaver/FileSaver.min.js:/*! @source http://purl.eligrey.com/github/FileSaver.js/blob/master/FileSaver.js */
share/index.html:<script type="application/javascript" src="../lib/filesaver/FileSaver.min.js"></script>
```

we can also use npm to install these packages. So it'll not ship on project tree but it'll be installed when installation script run.

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/releases/tag/1.1.8
