### ISSUE TITLE
Message details from shared link are empty

### ISSUE THREAD

**Issue by giavac** [sipcapture/homer-ui#90]
This can be reproduced with an installation from scratch (with bash installer) on debian jessie (`Linux debian-1gb-lon1-01 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux`).

homer-ui: `2f2baee`

homer-api: `7238223`

Step to reproduce: perform a Search. Click on Call-ID of search results to generate the Call flow. Click on Export, then Share Link. Copy shared link. Paste shared link into another tab (ensure the URL is correct).

The shared call flow is displayed correctly, but clicking on a message produces an empty modal window instead of the message details:

<img width="1435" alt="screen shot 2016-12-19 at 16 38 00" src="https://cloud.githubusercontent.com/assets/3305097/21318712/a935d5ec-c60a-11e6-8f59-7514982decf4.png">

There isn't any API query performed.

Going back to the call flow from the Search, clicking on the message shows instead its details:

<img width="1429" alt="screen shot 2016-12-19 at 16 37 44" src="https://cloud.githubusercontent.com/assets/3305097/21318749/cf9263a4-c60a-11e6-865f-3713738739c7.png">

It's also possible to see the API query, e.g.:

```
POST /api/v1/search/method HTTP/1.1.
Host: xxxxxxxx.
Connection: keep-alive.
Content-Length: 206.
Accept: application/json, text/plain, */*.
Origin: http://xxxxxxx.
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36.
Content-Type: application/json;charset=UTF-8.
DNT: 1.
Referer: http://xxxxxxx/.
Accept-Encoding: gzip, deflate.
Accept-Language: en-US,en;q=0.8,it;q=0.6,fr;q=0.4.
Cookie: HOMERSESSID=me07ehd1humqn17hni6asc1295.
.
{"timestamp":{"from":1482161297000,"to":1482161297000},"param":{"search":{"id":1,"callid":"8bhmklz0k9@127.0.0.1"},"location":{"node":"single"},"transaction":{"call":true,"registration":false,"rest":false}}}
```

I've spent some time on this but couldn't understand the root cause. What I noticed is that `share/controller.js` tries to use the data provided at the moment of the click, i.e. here:

https://github.com/sipcapture/homer-ui/blob/master/share/controller.js#L151

and at the moment of loading the data doesn't try to do a search to get the message details:

https://github.com/sipcapture/homer-ui/blob/master/share/controller.js#L546

This causes an exception, because `sdata.msg` (line 587) is null and "HTMLifying" it can't work:

```TypeError: Cannot read property 'split' of undefined
    at swapText (controller.js:561)
    at new <anonymous> (controller.js:587)
    at e (angular.js:4523)
    at Object.instantiate (angular.js:4531)
    at angular.js:9197
    at homerModal.min.js:12
    at b.$emit (angular.js:16301)
    at angular.js:24410
    at angular.js:14792
    at r.$eval (angular.js:16052)
```

The generic controller (`modules/pages/controllers/dialogCtrl.js`), instead, passes a search data structure:

https://github.com/sipcapture/homer-ui/blob/master/js/modules/pages/controllers/dialogCtrl.js#L368

and associates a search call to the resulting modal window callback:

https://github.com/sipcapture/homer-ui/blob/master/js/modules/pages/controllers/dialogCtrl.js#L49

I still have a clean installation dedicated to this issue, so just let me know in case any new detail or experiment is required. Thanks.

**Comment by UjjwalaVuyyala** [comment]
Hello giavac, 
          Please try setting ```define('SHARE_MESSAGES', 0);``` to ```define('SHARE_MESSAGES', 1);``` in preferences.php and reloading. Thanks.
