### ISSUE TITLE
ISUP Search Widget

### ISSUE THREAD

**Issue by lmangani** [sipcapture/homer-ui#91]
@zecke in reference to [isup_capture](https://github.com/sipcapture/homer-api/commit/5235ea12597a46470234d8092152862d2e051c96) could you help form a list of fields + description to implement the ISUP search widget in homer-ui?

**Comment by ishmaelen** [comment]
Forgive me for jumping in but I've got a suggestion that can be used as a starting point.

column | description
------------ | -------------
date|Date
correlation_id|Correlation ID
method|MSG/Type (IAM,ACM,ANM,CPG,REL,RLC,SAM)
calling_number|Calling Number
calling_ton|Calling Number TON (Type of number)
called_number|Called Number
called_ton|Called Number TON (Type of number)
cic|Circuit ID
cause_itu_cause|Cause Value
opc|Originating point code (OPC)
dpc|Destination point code (DPC)
proto|Protocol

Just a suggestion on the side while at it.. :) 
Would be nice to have an alias feature for OPC/DPC and searchable "OPC NI" and "DPC NI".

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/releases/tag/1.1.8
