### ISSUE TITLE
admin*.html: status should be a string model and rest api needs to be adjusted

### ISSUE THREAD

**Issue by zecke** [sipcapture/homer-ui#93]
When editing an alias (but applies to anything with status) the checkbox is not enabled. The API works with 0/1 as numbers but the REST query seems to return it as string. I noticed that

```
<input ng-model="newalias.status" ng-value="true" type="checkbox" ng-init="newalias.status=1" ng-true-value="1" ng-false-value="0">
```

should be:

```
...ng-true-value="'1'" ng-false-value="'0'"
```

to make it a string model. But when doing this the RestApi needs a change too because a status=FALSE will be omitted from the SQL query. I noticed/debugged this introducing  a new boolean to the adminalias.

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/releases/tag/1.1.8
