### ISSUE TITLE
QoS MOS missing after rotate

### ISSUE THREAD

**Issue by Si-Richards** [sipcapture/homer-ui#99]
Setup HOMER 5.0.5 on Centos7 (Captagent6, Kamailio5 Asterisk 13) and everything was perfect until the 1st rotate.

Homer Stopped showing the collected data and Kamalio threw SQL insert error so I realised the MYSQL socket path is incorrect for RHEL and I changed to "socket = /var/lib/mysql/mysql.sock"

I am now collecting everything but the QoS and MoS is not in the Homer UI.... report_capture is empty any ideas on what went wrong ?

**Comment by Si-Richards** [comment]
I also realised that the Rotate did not create the rtcp_capture tables in advance as stated in the rotation.ini but did for the others.

If i manually create the table it inserts the data but still it doesn't show QoS in the UI.

Ideas anyone?

**Comment by adubovikov** [comment]
I am not sure this can help, because to store rtcp packets into rtcp_capture_all_YYYYMMDD, requires
kamailio5 or opensips2

https://github.com/sipcapture/homer-api/blob/master/scripts/mysql/rotation_kamailio5.ini#L34

**Comment by Si-Richards** [comment]
Hi Alexandr,
Sorry, yes i have Kamailio5 running too. Today I have noticed that the rotation script worked again but the tables are missing the word **"all"** so the SQL insert fails.  

Where can i amend this? I looked at the Rotate Perl script but it didn't work.

**ERROR: db_mysql [km_dbase.c:128]: db_mysql_submit_query(): driver error on query: Table 'homer_data.rtcp_capture_all_20170822' doesn't exist (1146)**

**Comment by Si-Richards** [comment]
![image](https://user-images.githubusercontent.com/20224397/29557969-a4222946-8722-11e7-8110-7ca9a505a161.png)

**Comment by adubovikov** [comment]
did you event check my link ?

https://github.com/sipcapture/homer-api/blob/master/scripts/mysql/rotation_kamailio5.ini#L34

**Comment by Si-Richards** [comment]
Ahhh 👍 my fault.... perfect
